### ISSUE TITLE
Label out of the input

### ISSUE THREAD

**Issue by LM450N** [PolymerElements/paper-input#10]
I tried the `paper-input` element on Chrome 42 on Linux and the labels are all at the top left corner.

![label-out-of-input](https://cloud.githubusercontent.com/assets/2325091/7419698/29ebf430-ef77-11e4-87e6-0072b1e4954c.png)

**Comment by notwaldorf** [comment]
Eeeek I'll fix it right now. It's from yesterday's change to `iron-flex-layout`. Sorry!
