### ISSUE TITLE
paper-input underline no longer reflect focus

### ISSUE THREAD

**Issue by david-saslawsky** [PolymerElements/paper-input#108]
Try to set the focus on input elements in https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html, the underline no longer animate to show the element with focus.

I think it may have something to do with the capturing event listener both in `paper-input-container` and in `IronControlState` (imported through `paper-input-behavior`). See:

``
this.addEventListener('focus', this._boundOnFocus, true);
``

**Comment by morethanreal** [comment]
This is a duplicate of https://github.com/PolymerElements/paper-input/issues/99.

**Comment by notwaldorf** [comment]
Closing as duplicate
