### ISSUE TITLE
labeling mismatch for screen readers

### ISSUE THREAD

**Issue by johndjones** [PolymerElements/paper-input#113]
The algorithm that creates an ID on the label (used in aria-labelledby on the input) doesn't guarantee unique IDs, and when 2 labels get the same ID, the first is read (by ChromeVox) as the label for both inputs.

For example, if I have two inputs:
```html
<paper-input label="Name" value="{{user.name}}"></paper-input>
<paper-input label="Address" value="{{user.address}}"></paper-input>
```
...it occasionally happens that both labels have the same ID, and then I hear "name" before the content of both inputs when I read them in ChromeVox.

I think the problem is in the implementation of [paper-input-behavior._updateAriaLabelledBy](https://github.com/PolymerElements/paper-input/blob/master/paper-input-behavior.html#L348), which uses the clock to generate IDs:
```javascript
labelledBy = 'paper-input-label-' + new Date().getUTCMilliseconds();
```

It needs  a more robust calculation, maybe like the one it uses to generate an [ID for the add-on](https://github.com/PolymerElements/paper-input/blob/master/paper-input-behavior.html#L291) (though even that looks like it could have ID collisions):
```javascript
var id = 'paper-input-add-on-' + Math.floor((Math.random() * 100000));
```

**Comment by notwaldorf** [comment]
We should probably use a monotonically increasing ID instead.

**Comment by mkazlauskas** [comment]
How about `new Date().getTime()`?

**Comment by notwaldorf** [comment]
@mkazlauskas That's basically what we're doing now (https://github.com/PolymerElements/paper-input/blob/master/paper-input-behavior.html#L510) and it causes collisions

**Comment by mkazlauskas** [comment]
@notwaldorf it's not the same:

```js
new Date().getUTCMilliseconds() => 273
new Date().getTime() => 1457590172771
```

The reason of collisions is not because it's time based, it's because it's [0-1000)
