### ISSUE TITLE
Material Design focus highlighting not taking effect

### ISSUE THREAD

**Issue by nikwhite** [PolymerElements/paper-input#118]
http://www.google.com/design/spec/components/text-fields.html#text-fields-multi-line-text-field

paper-input-container.html
```javascript
this.addEventListener('focus', this._boundOnFocus, true);
this.addEventListener('blur', this._boundOnBlur, true);
```

These events don't bubble, so their listeners are never fired. Using focusin and focusout, the bubbling variants, seems to make this work as defined in the MD spec.

Will you accept a PR?

**Comment by notwaldorf** [comment]
I think this has been fixed in a recent release. Could you double check it works for you, please? Thanks!

**Comment by notwaldorf** [comment]
Closing, since it's super old and without updates.
