### ISSUE TITLE
Support for min and max

### ISSUE THREAD

**Issue by Mygod** [PolymerElements/paper-input#121]
e.g. `<paper-input min="1" max="5" type="number"></paper-input>`.

**Comment by Mygod** [comment]
Oh just realized that it has been fixed. Thanks.

**Comment by lexetam** [comment]
min max work with up and downs keys, but not for input directly form keyboard

**Comment by omarllorens** [comment]
Sorry for write on  a close issue, but I'm interested on the last comment, I have the same problem.
I'm using min=0 to not permit negative numbers but just works with the up down buttons, if you write a negative number from keyboard you can do it without problem.
