### ISSUE TITLE
paper-textarea does not include IronFormElementBehavior

### ISSUE THREAD

**Issue by sfeast** [PolymerElements/paper-input#127]
I see it was taken out here - https://github.com/PolymerElements/paper-input/commit/ca35d79a916a8e971e12b6026e671fd13c23f846 - for de-duplication purposes but I don't think it is getting IronFormElementBehavior elsewhere. So now it isn't picked up by iron-form.

Additionally, & perhaps another bug is needed for this, it doesn't look like calls to validate() on paper-textarea are actually working either. I haven't debugged for the exact reason but the call always returns undefined.

**Comment by notwaldorf** [comment]
@sfeast `paper-textarea` gets its name and value from the underlying `iron-autogrow-textarea`, which does have and `IronFormElementBehavior` and should get picked up by the form. 

I added this to the `iron-form` demo:
```
<paper-textarea name="foo" required label="bar"></paper-textarea>
```
And the value is submitted correctly (and `required` is taken into consideration`)

Would you mind doing a `bower cache clean && bower install` to make sure you've got the latest version?

**Comment by sfeast** [comment]
Ah my mistake, I didn't update the dependencies, ```IronFormElementBehavior``` is there in iron-autogrow-textarea now & yes, required is taken into consideration as well. Sorry about that & thank you for the explanation!

**Comment by gertcuykens** [comment]
hmm i am having the same issue here, is there something more specific then `bower cache clean && bower install` please?

**Comment by notwaldorf** [comment]
@gertcuykens I've just added this to `iron-form`, and it worked fine:
```
<paper-textarea name="area" label="typetytype" required></paper-textarea>
```

I've done a new release of `iron-form` just in case there was a fix in master related to this. If it still doesn't work, can you show me some code snippets to see what's going on?

**Comment by gertcuykens** [comment]
Can you try `myform.addEventListener('submitXhr', function(e) {var data = new FormData(e.target)... xhr.send(data)}`

**Comment by notwaldorf** [comment]
I don't see why that would work. You have to use an `iron-form`, not a plain form, if you want it to track custom elements, and you have to use the `iron-form`'s submit method (or its `serialize`) to get the serialized that. Whatever `FormData` does, it will only look at the form's native HTML elements, which do not include `paper-textarea`.

Here's the `iron-form` demo for an example: https://github.com/PolymerElements/iron-form/blob/master/demo/index.html#L38

**Comment by gertcuykens** [comment]
It does work for al my other paper-input stuff?

**Comment by notwaldorf** [comment]
Yes, but that's just a fortunate coincidence. `paper-input` has an underlying native `<input>` element, which automatically registers itself to a native form. 

If you want to use custom elements inside a form, you _have_ to use an `iron-form`. Native forms only register `<input>` elements and nothing else.

**Comment by gertcuykens** [comment]
wel that would explain allot :D haha thanks, saved me allot of trouble messing around with bower install :P

**Comment by notwaldorf** [comment]
No worries! Glad I could help!

**Comment by prgpascal** [comment]
Hi!
I've an issue with the "name" attribute in **paper-textarea**. My code is:
```
<paper-textarea name="message" rows="5" label="Message"></paper-textarea>
```
On my browser I inspect the page and I can see that **iron-autogrow-textarea** gets the "name" and "rows" attributes. 
But the **textarea** gets only the "rows" attribute... not the "name" attribute. So when I submit the form it doesn't work.
```
<iron-autogrow-textarea id="input" class="paper-input-input style-scope paper-textarea" aria-disabled="false" autocomplete="off" placeholder="" autocapitalize="none" rows="5" max-rows="0" name="message">
    <!-- the mirror sizes the input/textarea so it grows with typing -->
    <div id="mirror" class="mirror-text style-scope iron-autogrow-textarea" aria-hidden="true"><br><br><br><br>&nbsp;</div>

    <!-- size the input/textarea with a div, because the textarea has intrinsic size in ff -->
    <div class="textarea-container fit style-scope iron-autogrow-textarea">
      <textarea id="textarea" class="style-scope iron-autogrow-textarea" rows="5" autocomplete="off" placeholder="" aria-describedby="" aria-labelledby="paper-input-label-948"></textarea>
    </div>
</iron-autogrow-textarea>
```

I've also used **paper-input** elements: they work perfectly and the **input** elements get the "name" attributes without problems.

How can I solve this? :(
Thank you :)

**Comment by gertcuykens** [comment]
Here is a quick work around see if this work for you

```
<input type="hidden" name="test" value="{{text}}">
<paper-textarea value="{{text}}"></paper-textarea>
```
