### ISSUE TITLE
missing focus() method

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/paper-input#129]
Currently there is no way to programmatically focus a `paper-input`.

**Comment by kungufli** [comment]
@frankiefu you're right, but as a workaroud for now you can call `focus()` directly on the `<input>` element inside the `paper-input`: 
```
this.$.yourpaperinput.$$("input").focus();
```

**Comment by robdodson** [comment]
wow this is really not awesome. @tjsavage can we prioritize this? I really need it
