### ISSUE TITLE
paper-textarea autoresize issue

### ISSUE THREAD

**Issue by jscissr** [PolymerElements/paper-input#130]
Steps to reproduce:

1. open Google Chrome
1. go to https://elements.polymer-project.org/bower_components/paper-input/demo/index.html
1. fill a line of the textarea just to the point before it overflows to the next line
1. press enter

You can now see a vertical scrollbar on the textarea.

It seems that Chrome shows the scrollbar even tough it isn't necessary, without it there would be enough space for the line of text.  It's a bit like a chicken-and-egg problem: Because there is a scrollbar (which uses horizontal space), the text wraps. Because the text wraps, there is a scrollbar.

![screenshot](https://cloud.githubusercontent.com/assets/4520820/8914783/7d4761cc-34a1-11e5-92eb-15489222cffb.png)

**Comment by kungufli** [comment]
This seems to be related also to https://github.com/PolymerElements/paper-input/issues/125

**Comment by jscissr** [comment]
Yes, it's the same as the GIF in [this comment] (https://github.com/PolymerElements/paper-input/issues/125#issuecomment-125519600), but I think #125 is about disabling horizontal autoresizing in dialogs.

**Comment by notwaldorf** [comment]
@jscissr Blerg. I see what you mean. I agree that it's a bug, but it's such an edge case that I can't promise I will get to it very soon. If you think of a solution, please send me a PR and I can take a look at it, but I don't have any ideas off the bat about how to fix this quickly. 😿

**Comment by jscissr** [comment]
I guess it's even a bug in Chrome, not paper-input; I couldn't reproduce in Firefox.
IE however shows disabled scrollbars:
![image](https://cloud.githubusercontent.com/assets/4520820/9070214/8a22dcac-3aee-11e5-9afa-9c99498ee145.png)
I can open an issue for that if you like.

**Comment by jscissr** [comment]
I found the bug in Chrome: https://crbug.com/240772

**Comment by notwaldorf** [comment]
Closing this, since it seems to be fixed in Chrome now (and it wasn't a Polymer bug to begin with).
Please re-open if this is still happening!

**Comment by tsiki** [comment]
This bug seems to have reappeared.
