### ISSUE TITLE
Weird behavior with paper-textarea

### ISSUE THREAD

**Issue by Iskalla** [PolymerElements/paper-input#132]
I'm seeing what I think is an strange behavior on a paper textarea, when it has something written in it, writing anything more causes it to show only one word at a time until it reaches the end of the first line,  then it behaves normally (I think). Is this intended? Am I doing something wrong?

Here's a gif showing what I mean:

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/11649446/9002272/1e1bd08e-3762-11e5-9c13-38c9b59ba133.gif)

**Comment by notwaldorf** [comment]
I can't repro this locally. Can you show repro this in jsbin, or show me some code about how you create your textarea/style it/ set its initial value, please?

**Comment by kungufli** [comment]
Seems the same problem reported here https://github.com/PolymerElements/paper-input/issues/125

**Comment by Iskalla** [comment]
The textarea is inside another element called custom-form-elem, which gets info from a database column and, based on that column properties, does one thing or another (i.e. shows a paper-input, a textarea, a datepicker, etc.).
As you may have noticed, on my previous post the textarea was inside a paper-dialog, meaning it could be the same problem as #125 , but today I used it on a plain div and saw the same exact problem, so I guess it has something to do with being inside another element?

Here's some code showing how I've done it:

    <dom-module id="custom-form-elem">
    <style>
        [here's some style unrelated to the textarea or the component itself]
    </style>
    <template>
        <div class$="{{setcontentclass(size)}}">
            [some more conditional code...]
            <template is="dom-if" if="{{islongalphab(col)}}">
                <paper-textarea label="{{setcolname(col)}}" id="input" bind-value="{{colvalue}}"  disabled$="{{readonly}}" required$="{{col.Required}}"></paper-textarea>
            </template>
        </div>
    </template>
    <script>
        Polymer({
            is: "custom-form-elem",
            properties: {
                [some more properties...]
                colvalue: {
                    type: String,
                    value: "",
                    observer: 'colvalueChanged',
                    reflectToAttribute: true,
                    notify: true
                }                
            },
            [some more check functions]
            islongalphab: function (column) {
                if (column.Maxlength > 50)
                    return true;
                else
                    return false;
            }


I have a colvalueChanged function but it only does stuff with "special" columns like datepickers or selects, nothing to do with the text area, which value is automatically filled when colvalue is setted.

As for outside code, I just load all columns at once, then all the content. This means that first I get the "form" with all content blank, then fill the values for each element.
This is what I do to load every custom-form-elem:

    <div class="vertical layout">
        <template is="dom-repeat" items="{{profilecols}}" as="col">
            <custom-form-elem col="{{col}}" colid="{{col.ColumnId}}" readonly="false"></custom-form-elem> 
        </template>
    </div>

when I get the data for each column, I just iterate over every custom-form-elem "colid" property, and fill it's colvalue, like this:

    var customcols = Polymer.dom(this.root).querySelectorAll('custom-form-elem');
    for (var i = 0; i < customcols.length; i++) {
        customcols[i].colvalue = this.profile[customcols[i].colid];
     }

**Comment by notwaldorf** [comment]
Yeah, this is related to #125. My fix for that is to set a width on the `paper-dialog` so that it doesn't try to accommodate the ever-growing textarea:
```
paper-dialog {
  width: 300px;
 }
```

**Comment by notwaldorf** [comment]
I'm going to mark this as a duplicate for #125 because I'm typing the same comments twice :)
