### ISSUE TITLE
Adding noLabelFloat to a paper-input doesn't seem to have any effect

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/paper-input#139]
The following bit of code still produces a floating label when I interact with it. `<paper-input noLabelFloat label="Add an item"></paper-input>`

**Comment by notwaldorf** [comment]
@robdodson ah, you got bit by dash-case-not-camel-case. It's `no-label-float` :)

**Comment by robdodson** [comment]
ah darn it! I always do that :P

**Comment by abhilash29** [comment]
How to disable the underline?
