### ISSUE TITLE
Bind input `value`

### ISSUE THREAD

**Issue by teckays** [PolymerElements/paper-input#14]
I have the following code:

```html
<form id="search" action="/search/{{q}}" method="get">
    <paper-input no-label-float label="search" value="{{q}}"></paper-input>
</form>
```

On the (old), `paper-input` I could bind the `q` variable from the input value directly to the `action="/search/{{q}}"` so that when I submit the form I have the input value binded properly. Ho to achieve it with your `paper-input` component?

**Comment by morethanreal** [comment]
Sub-property binding is not supported in Polymer 0.8. (See the "binding limitations" section in the [migration notes](https://github.com/Polymer/polymer/blob/0.8-preview/PRIMER.md#migration-notes)). You can use a computed property instead:

```html
<!-- in the element template -->
<form action="[[_computeFormAction(value)]]" method="get">
  <paper-input label="label" value="{{value}}"></paper-input>
</form>
```

```js
/* in the element prototype */
_computeFormAction: function(value) {
  return '/search/' + value;
}
```
