### ISSUE TITLE
paper-textarea losing focus on Internet Explorer

### ISSUE THREAD

**Issue by moduv5** [PolymerElements/paper-input#144]
Steps to reproduce:

1.	Open Internet explorer
2.	Go to https://elements.polymer-project.org/bower_components/paper-input/demo/index.html
3.	Type some words, press enter, type other words
4.	Go on the first word and type some letters.

The focus of the text area is always going at the end.
The same thing happen when we use backspace on a word at the beginning.
I am on Windows 8.1 (I test it on Windows 10 and it seems to have no problem on Internet Explorer)

**Comment by notwaldorf** [comment]
I can't repro this anymore, so I think this has already been fixed.
