### ISSUE TITLE
updateValueAndPreserveCaret doesn't work for `paper-textarea`.

### ISSUE THREAD

**Issue by jakemac53** [PolymerElements/paper-input#152]
[The test](https://github.com/PolymerElements/paper-input/blob/master/test/paper-textarea.html#L94) is actually cheating, its assigning `selectionStart` and `selectionEnd` properties on the `iron-autogrow-textarea` element directly, which doesn't do anything, see https://github.com/PolymerElements/paper-input/pull/151.

**Comment by notwaldorf** [comment]
This should be fixed
