### ISSUE TITLE
Label doesn't utilize full component width; Long labels get wrapped unnecessarily.

### ISSUE THREAD

**Issue by miztroh** [PolymerElements/paper-input#154]
This is from the demo page.  I just changed the label property of the first paper-input on the page.

![paper-input](https://cloud.githubusercontent.com/assets/2515209/9391854/f2c46abc-473e-11e5-9505-00132dedcd3d.jpg)

**Comment by notwaldorf** [comment]
This should be fixed by https://github.com/PolymerElements/paper-input/pull/193
