### ISSUE TITLE
paper-textarea does not respect max-rows

### ISSUE THREAD

**Issue by anthonytordillos** [PolymerElements/paper-input#158]
Looks like the demo of this functionality in the elements catalog is broken: https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html

**Comment by notwaldorf** [comment]
What browser are you seeing this on? When I use the textarea that has `max-rows="4"` set, then it starts scrolling once they're hit:

![teaxtarea](https://cloud.githubusercontent.com/assets/1369170/9476205/575b7f8a-4b20-11e5-8995-246bbb8b4507.gif)

**Comment by anthonytordillos** [comment]
It looks like the behavior is correct when you have newlines in the text. The case I'm describing is when you have long text that wraps to multiple lines:

![textarea](https://cloud.githubusercontent.com/assets/1113203/9476835/c0cf7ca2-4b23-11e5-86d5-6588060eb7ae.png)

Based on the description of the maxRows property (The maximum number of rows this element can grow to until it scrolls.) I would expect it to scroll once the text has wrapped past maxRows lines.

**Comment by notwaldorf** [comment]
Ah, yes, I think that's related to https://github.com/PolymerElements/iron-autogrow-textarea/issues/32

**Comment by anthonytordillos** [comment]
Yup. I agree with nloewen's conclusion that constrain should line wraps into account.

**Comment by theDataWhore** [comment]
so max-rows counts the new lines instead of the 'visible' row counts?

**Comment by notwaldorf** [comment]
You should use `maxRows` as a JavaScript property , and `max-rows` as an attribute in HTML: https://www.polymer-project.org/1.0/docs/devguide/properties.html#property-name-mapping

Closing this, since it seems to be an underlying `iron-autogrow-textarea` bug,

**Comment by faan11** [comment]
A solution would be to block the height of the iron-autogrow-textarea. It works but you have to compute the size in pixel.
```
:host{
      --paper-input-container-input:{
        max-height: 75px;
      }
 }
```
