### ISSUE TITLE
Change event doesn't fire in Polymer.dom='shadow' 

### ISSUE THREAD

**Issue by blasten** [PolymerElements/paper-input#161]
Reference: https://github.com/PolymerElements/paper-slider/issues/54. 

Also useful: http://w3c.github.io/webcomponents/spec/shadow/#events-that-are-not-leaked-into-ancestor-trees

**Comment by notwaldorf** [comment]
@blasten I thought this is what https://github.com/PolymerElements/paper-input/pull/142 was trying to fix?

**Comment by blasten** [comment]
@notwaldorf right, this issue is for tracking. :)

**Comment by mgiuffrida** [comment]
:+1:

**Comment by notwaldorf** [comment]
This has been fixed in #168

**Comment by notwaldorf** [comment]
This has been fixed in #168
