### ISSUE TITLE
Autofocus not working in Firefox

### ISSUE THREAD

**Issue by pkaske** [PolymerElements/paper-input#166]
Firefox seems to evaluate `autofocus` only at page load. As this attribute is applied by `paper-input` after page load, firefox never takes notice of it.

Here's a [JSBin](http://output.jsbin.com/camosonafo)
It show's the raw output, because autofocus seems not to work at all in the edit mode of JSBin.

Cheers

**Comment by zmoshansky** [comment]
Under Linux Chrome 45.xxxx it works the first time the element is rendered, but not after. 

Ex.) Showing a search bar, the first time it's shown it works great, but if it's `hidden=true` and shown again, it no longer auto-focuses.

**Comment by notwaldorf** [comment]
The problem is that FF doesn't focus the input correctly after the attribute has been set (which Chrome does): http://jsbin.com/vihusaxoha/edit?html,output.

I think `iron-input` should maybe have a listener for `autofocus` and refocus itself manually to work around this.

**Comment by bicknellr** [comment]
([spec link](https://html.spec.whatwg.org/multipage/forms.html#autofocusing-a-form-control:-the-autofocus-attribute))

**Comment by z2oh** [comment]
I see that this issue has been closed for quite some time now... I am having trouble with the `autofocus` attribute in all browsers but Chrome. Is there some other requirement to get `autofocus` to work?
