### ISSUE TITLE
Consider optimizing performance

### ISSUE THREAD

**Issue by sorvell** [PolymerElements/paper-input#167]
Since users often create many instances of this element, it will especially benefit from performance optimization. Consider lazily creating optional or user initiated functionality (e.g. paper-ripple), leveraging behaviors over composition (e.g. paper-material), streamlining styling, and eliminating or simplifying features (e.g. behaviors)

**Comment by esprehn** [comment]
The offsetParent in the template callback also causes a flood of style recalcs, one for every paper-input-container in the page:
https://github.com/PolymerElements/paper-input/blob/master/paper-input-container.html#L534

**Comment by notwaldorf** [comment]
@esprehn Ah, that's my bad. This should only happen when `this.$.prefix` is true, but the bit that should bail out is last in the `if` statement. I'll move it to the top so that most of the time we don't even check if label has an `offsetParent`

**Comment by esprehn** [comment]
@notwaldorf That still forces a synchronous recalc when the prefix is set, and also a synchronous distribution update since you call getDistributedNodes, polymer should really defer this work until requestAnimationFrame, and should batch the reads (calls to getDistributedNodes && offsetParent) and the writes of setting style.left

**Comment by notwaldorf** [comment]
@sorvell should this still be open? this doesn't use `paper-ripple` nor `paper-material`, and I cleaned up the cray offset calcs

**Comment by notwaldorf** [comment]
Closing, we've started working on https://github.com/PolymerElements/paper-text-field as a refactor, efficient version of this element
