### ISSUE TITLE
Documentation should reflect that pattern and allowed-pattern have different semantics

### ISSUE THREAD

**Issue by CSEMike** [PolymerElements/paper-input#169]
In [issue 190](https://github.com/Polymer/paper-input/issues/190), it was revealed that the pattern and allowed-pattern mean completely different things:

* `pattern` is a regular expression that works with auto-validate and error-message.
* `allowed-pattern` is *not* a regular expression. It is something else, a pattern, with nebulous semantics.

I could not find any information in the documentation about the semantics of allowed-pattern. Perhaps I am missing something.

It is confusing that both "pattern" and "allowed-pattern" are attributes on an input that control validation.
It is even more confusing that "pattern" accepts a regular expression but "allowed-pattern" does not.

I would hope that this distinction could be rationalized in the API. But, failing that, at least the documentation should clearly state the limitations of allowed-pattern vs pattern.

**Comment by notwaldorf** [comment]
@CSEMike oh, thanks so much! There's a tool we could have used, but this is excellent too! :tada:  :)

**Comment by notwaldorf** [comment]
The docs in `iron-icon` (where the property lives) have been updated: https://github.com/PolymerElements/iron-input/blob/master/iron-input.html#L81
