### ISSUE TITLE
Support for valueAsNumber property

### ISSUE THREAD

**Issue by johan12345** [PolymerElements/paper-input#170]
Like suggested in Polymer/polymer#1996, I am using an `iron-input`'s `valueAsNumber` property for two-way data binding to a value of type `Number` (called `theValue` in the example below) in my JSON model:

```html
<input is="iron-input" type="number" value-as-number="{{theValue::input}}">
```

I would like to replace this input with a `paper-input`. However, `paper-input` does not seem to support the `valueAsNumber` property. Could this be added? Or is there another way to bind a `paper-input`'s value to a number instead of a string?

**Comment by notwaldorf** [comment]
I will look into binding it, but I think for now you could just do `yourPaperInput.inputElement.valueAsNumber` to access it

**Comment by notwaldorf** [comment]
Closing, as the solution is really really horrible (see the discussion in #236 and PolymerElements/iron-input#58)
