### ISSUE TITLE
Documentation is wrong; mentions iron-input-valid

### ISSUE THREAD

**Issue by dplassgit** [PolymerElements/paper-input#174]
On https://github.com/PolymerElements/paper-input/blob/master/paper-input-container.html#L331 it says the invalid "property is set automatically when the input value changes if auto-validating, or when the iron-input-valid event is heard from a child."  However, the event name should be iron-input-validate (https://github.com/PolymerElements/paper-input/blob/master/paper-input-container.html#L397)

**Comment by notwaldorf** [comment]
Yup, you're totally right. On it!
