### ISSUE TITLE
When an input has an error set, the text after it renders with an offset the length of the error

### ISSUE THREAD

**Issue by lkovaleva** [PolymerElements/paper-input#175]
Code:
`<paper-input id="input"  label="Number input" pattern="\d+" auto-validate error-message="Please enter a number"></paper-input>`
`<div>Some label</div>`

Rendered:
![image](https://cloud.githubusercontent.com/assets/14207087/9775354/50cd9858-5703-11e5-9a8f-f807dd22e8d0.png)

The line right after the input is offset by the length of the error (when error is visible or not).

It looks like simply removing "float: left" from paper-input-error fixes this, but I'm not sure if that would cause any other adverse effect.

**Comment by notwaldorf** [comment]
@lkovaleva As a quick fix, while I'm trying to figure out what's going on, adding this seems to fix it: `paper-input { display: inline-block; }`
