### ISSUE TITLE
Using an iron-autogrow-textarea inside a paper-input-container doesn't work

### ISSUE THREAD

**Issue by dplassgit** [PolymerElements/paper-input#177]
Specifically:
1. The label isn't styled
2. The label and textarea overlap
3. The textarea is not styled

This code code is what I was using:

```html
<paper-input-container>
  <label>paper-input-container fails</label>
  <iron-autogrow-textarea></iron-autogrow-textarea>
</paper-input-container>

<paper-textarea label="paper-textarea works">
</paper-textarea>
```

Link to polybin: [http://go/iron-autogrow-fail ](http://go/iron-autogrow-fail)

**Comment by notwaldorf** [comment]
@dplassgit I think it's just a matter of applying the right styles. If I add this class to your textarea, then it looks and works the same.
```
<iron-autogrow-textarea class="paper-input-input"></iron-autogrow-textarea>
```

(also slight, nitpicky note: please don't use go/ links in github issues. GitHub is 100% public, and these links aren't accessible by everyone. Thanks!

**Comment by dplassgit** [comment]
Thanks for the workaround. This should be documented on the paper-input-container page.
