### ISSUE TITLE
Add type "search" to paper-input

### ISSUE THREAD

**Issue by Waxolunist** [PolymerElements/paper-input#178]
Currently the type search is not allowed. Only number, password and text are allowed.
The type search would allow on iPhone to show on the keyboard instead of "Return" to display "Search".
Is it possible to add this behavior?

**Comment by notwaldorf** [comment]
`type=search` seeeeeems to work, it just has a bit of a layout bug :)
```html
<paper-input label="label" type="search"></paper-input>
```
produces
<img width="298" alt="screen shot 2015-09-23 at 1 01 44 pm" src="https://cloud.githubusercontent.com/assets/1369170/10057075/462484d4-61f3-11e5-818e-4d07d80eea23.png">

I think the offset comes from the native html input which styles the "type=search" element differently :sob:
<img width="169" alt="screen shot 2015-09-23 at 1 06 12 pm" src="https://cloud.githubusercontent.com/assets/1369170/10057215/edec140c-61f3-11e5-8cc2-50f90444f3e3.png">

I'll take a look. Does everything else work fine for you, though?

**Comment by notwaldorf** [comment]
I've also opened https://github.com/PolymerElements/paper-input/pull/182 to fix the styling a bit. The styling is still not great because browsers.

**Comment by Waxolunist** [comment]
I added following to my css:

```

input[type=text]::-ms-clear {
  display: none;
  width: 0;
  height: 0;
}

input[type=text]::-ms-reveal {
  display: none;
  width: 0;
  height: 0;
}

input[type="search"]::-webkit-search-decoration,
input[type="search"]::-webkit-search-cancel-button,
input[type="search"]::-webkit-search-results-button,
input[type="search"]::-webkit-search-results-decoration {
  display: none;
}

input[type="search"] {
  -webkit-appearance: none;
}
```

To show the word search on the keyboard on iPhone, the input type search has to be surrounded with a form tag, which has an action attribute. So search is working actually.

You can close this one.

**Comment by notwaldorf** [comment]
I've actually opened a PR to fix the styles, and add the results/auto save
attribute :)
