### ISSUE TITLE
If value changes from "" to "foo" when disabled, the label position isn't updated in FF

### ISSUE THREAD

**Issue by albinrangefelt** [PolymerElements/paper-input#179]
The following issue seems to affect FF (not Chrome, haven't checked Edge).

If setting a new value on an empty disabled <paper-input> element (with a label set), the label's position isn't updated to reflect the fact that the element now has a value. In the below screenshot, the first paper-input was enabled when the value was assigned, while the second one was disabled ("0" and "Rental price" is rendered on top of each-other).

![screenshot from 2015-09-18 15 19 19](https://cloud.githubusercontent.com/assets/280408/9960137/0a7974a4-5e19-11e5-9bcb-379812d44008.png)

**Comment by albinrangefelt** [comment]
Can also report that I see the same behavior in IE11/Edge.

**Comment by notwaldorf** [comment]
I think this may be related to https://github.com/PolymerElements/iron-input/issues/47. Let's see if this still happens after that PR lands.

**Comment by tracyf** [comment]
iron-input#47 looks like it hasn't been updated for almost 3 months, unless I'm missing something. Is there any progress being made?

**Comment by notwaldorf** [comment]
This is caused by PolymerElements/iron-input#47. I will pick it up from Kevin this week.
