### ISSUE TITLE
"autocomplete" doesn't seem to excist in "iron-input"

### ISSUE THREAD

**Issue by fooloomanzii** [PolymerElements/paper-input#181]
I can't see, how to use it or to find it in source code.

**Comment by notwaldorf** [comment]
`iron-input` is just a type extension of a regular `<input>` element, so it should work just like the native one. This, for example, will autocomplete any names:
```html
<input is="iron-input" autocomplete="on" name="fname">
```

And look like this:
<img width="314" alt="screen shot 2015-09-23 at 12 06 40 pm" src="https://cloud.githubusercontent.com/assets/1369170/10055529/942e275a-61eb-11e5-92d0-1b3bc82229cb.png">
