### ISSUE TITLE
paper-textarea focus/blur don't work properly

### ISSUE THREAD

**Issue by bbalas** [PolymerElements/paper-input#185]
Calling focus() on a paper-textarea doesn't work like it does for paper-input.  Also the blur event gets fired twice for paper-textarea.  This might have something to do with the shared behavior between paper-input and paper-textarea.

**Comment by fozziethebeat** [comment]
Anytime line on fixing this?  This is problematic for any UI that requires showing multiple textareas in a row that also need expanding heights.

**Comment by notwaldorf** [comment]
Duplicate of https://github.com/PolymerElements/paper-input/issues/129. There's already a PR in flight

**Comment by Fausto-theXS** [comment]
Still the blur event gets fired twice for paper-textarea.
Anyway of avoiding that?
