### ISSUE TITLE
Problem with paper-input inside paper-item

### ISSUE THREAD

**Issue by beppino** [PolymerElements/paper-input#188]
Hello,
I'm not sure if the problem is about paper-item or paper-input, but if I use a paper-input inside a paper-icon-item the input doesn't accept space character.
It's a new problem, from the last few days... Can please help me? I've an application in beta testing and my client ask me for a solution.
Thanks!
-g

**Comment by notwaldorf** [comment]
Closing this, as the correct issue is https://github.com/PolymerElements/paper-item/issues/28

**Comment by beppino** [comment]
Correct, thanks!
