### ISSUE TITLE
<paper-input type="date"> is not working in safari

### ISSUE THREAD

**Issue by boloson** [PolymerElements/paper-input#197]
I guess type="date" is supported by safari when using <input type="date">, however it is not working in safari for paper-input type="date".  Is this supposed to happen or is it a bug ?

**Comment by notwaldorf** [comment]
The native `<input type="date">` also does not work in Safari (http://jsbin.com/tomudunuzi/edit?html,output), so I don't think it's supported. `caniuse` confirms this: http://caniuse.com/#feat=input-datetime
