### ISSUE TITLE
Wrong custom css property name on online documentation

### ISSUE THREAD

**Issue by JustinXinLiu** [PolymerElements/paper-input#199]
On this [link](https://elements.polymer-project.org/elements/paper-input?active=paper-input-container
), it lists `--paper-input-container-input-disabled` as one of the custom css properties. But if you have a look at the source code it should really be `--paper-input-container-disabled`.

**Comment by notwaldorf** [comment]
This was already fixed in https://github.com/PolymerElements/paper-input/pull/194, will show up in the next catalog refresh.
