### ISSUE TITLE
The visual error state of a paper-input should be separated from the field's validation result until the field looses focus

### ISSUE THREAD

**Issue by grohjy** [PolymerElements/paper-input#200]
Example: I have a form with a required input and a submit button. The submit button should be inactive until input field is validated (invalid = false). A paper-input field is initiated with invalid=false value and therefore my submit-button is active when format comes to screen (if user hits enter or clicks the button, form is sent). Input-field validation kicks in when a user changes or leaves the field and the submit works as expected. 
I believe a good solution would be to separate invalid-state and the appearance of input-field  from each other ie. input-fields look should change only with on-blur or on-change. 
This solution also solves the annoying problem of auto-validating input fields, where input-field displays an error while user is filling out the field. With this solution validation is always in real time, but the look of an input-field changes only after the user leaves the field.

**Comment by notwaldorf** [comment]
Hmm, this sounds a bit weird to me. I think that as you're typing something, you should know when it's invalid. Imagine, for example, that you're typing a phone number, which only accepts digits, and you've suddenly typed a digit. I think the `paper-input` should tell you that as soon as you make the mistake, and not wait until you blur out.

I also think it's a bit weird if the underlying state of an input is invalid, but it is visually described as valid.

@tjsavage, what do you think?

**Comment by notwaldorf** [comment]
Closing this, as I don't think this is a feature e should add to paper-input, since it sort of obfuscates the validity UI of the input.
