### ISSUE TITLE
polylint not clean

### ISSUE THREAD

**Issue by duongphuhiep** [PolymerElements/paper-input#202]
I expect that all standard components are clean with polylint, but
```
bower_components/paper-input/paper-input.html:90:7
    Property '_ariaLabelledBy' bound to attribute 'aria-labelledby$' not found in 'properties' for element 'paper-input'
```

**Comment by notwaldorf** [comment]
Interesting. We define `_ariaLabelledBy` as a private-ish property inside a method, but I think we should add it to the properties block, just like we do for `_ariaDescribedBy`: https://github.com/PolymerElements/paper-input/blob/master/paper-input-behavior.html#L310

**Comment by duongphuhiep** [comment]
I don't understand why polylint want a private variable decalre in the property, 
It feels not right if we have to add codes only to sastify polylint but without real reason or usage. 
Many other components have the same issue, Maybe we should have to start by asking the polylint team the reason about this rule.. Is it too strict?

**Comment by notwaldorf** [comment]
I think polylint is right in this case. We're using a variable that we know exists from a behaviour, but that behaviour isn't actually declaring it in its properties block.

+ @rictic, our polylinter

**Comment by rictic** [comment]
+ @garlicnation too.

I don't have a super strong opinion here, but I lean towards declaring the property explicitly and polylint warning about this, otherwise it couldn't warn about misspelled properties.

**Comment by garlicnation** [comment]
@notwaldorf Polylint is right. The closure compiler will also complain about this, so it should be fixed.

+1 to polylint on all the repos!

**Comment by davidmaxwaterman** [comment]
It also generates noise on user's code - I get the same error on this file :

<https://github.com/01org/nlpljs/blob/mw-polymer-1.0-upgrade-2/example-app/app/content_push/cp-display.html>

It seems the error comes via the dependency on paper-slider (not all that obvious, tbh).

I'd be much happier is messages like this were only on my own code.
