### ISSUE TITLE
accept="image/*" 

### ISSUE THREAD

**Issue by kishaningithub** [PolymerElements/paper-input#206]
1) For Input type="file" the accept="image/*"  and "multiple" parameters are not propagated
    to the actual html input element. 
2) The Label placement is hiding below the "Browse" key.
![image](https://cloud.githubusercontent.com/assets/763760/10506003/bc64e230-7330-11e5-8eb0-77eb7ad2c651.png)

**Comment by notwaldorf** [comment]
For the UI bug, given that the UI of `<input type="file">` varies greatly across browsers, the best solutions is to always force the label to float:
```
<paper-input label="Choose a file!" always-float-label type="file"></paper-input>
```
