### ISSUE TITLE
The error label position:absolute makes it stuck in certain situations 

### ISSUE THREAD

**Issue by JustinCase1089** [PolymerElements/paper-input#213]
Hi
Have a look at this one: http://stackoverflow.com/questions/33101739/polymer-paper-input-scroll-issue
Is this a bug?
Cheers

**Comment by notwaldorf** [comment]
Yeah, it's definitely a bug :(

**Comment by JustinCase1089** [comment]
Thanks

**Comment by jab** [comment]
Just tried the [jsbin](http://jsbin.com/yakosizisa/edit?html,output) that was linked to from the SO page and it looks like this has been fixed. Close?

**Comment by JustinCase1089** [comment]
Yes, it can be closed
