### ISSUE TITLE
paper-textarea overflows in Firefox with single long word

### ISSUE THREAD

**Issue by lu2** [PolymerElements/paper-input#214]
paper-input 1.0.16
Firefox 41.0.2

In Firefox when the content of the paper-textarea is a single word longer than paper-textarea itself, it is not wrapped and overflows on the same line.

Observable also at https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html&active=paper-input
![papertextarea_overflows_ff](https://cloud.githubusercontent.com/assets/1437176/10716358/7ee8e182-7b36-11e5-8f59-bd3fa12c3a69.png)

**Comment by notwaldorf** [comment]
@robrez I think your fix for https://github.com/PolymerElements/paper-input/pull/276#issuecomment-169151225 will also fix this issue

**Comment by robrez** [comment]
Confirmed, it does fix this issue in FF 41.0.2

**Comment by lu2** [comment]
Thanks guys, with robrez's patch https://github.com/robrez/paper-input/commit/f5e467b9fcec5931ab1759fbc0a8763169c7252b the demo indeed works ok. However mine project is unaffected with this fix. It seems it is because mine paper-textarea is in flex container like this:
```html
<div style="display: flex;">
  <!--left column for fixed width picture-->
  <div style="flex: 0 0 auto; width:20px; background-color: black;"> ...
  </div>
  <!--right column for paper-textarea which should occupy rest of the screen-->
  <div style="flex: 1 1 0;">
    <paper-textarea label="autoresizing textarea input"></paper-textarea>
  </div>
</div>
```
and in that case the overflow in FF is still there.

But maybe I am just misusing flex... I guess this bug can be closed.

**Comment by robrez** [comment]
@lu2 It does fix the overflow problem..

I think you're seeing another unrelated problem where paper-textarea inside of a horizontal flex parent needs explicit sizing of some sort.

https://github.com/PolymerElements/paper-input/pull/276#issuecomment-169168240

Try this...
```
<link rel="import" href="../../iron-flex-layout/iron-flex-layout.html">
...
.h-flex {
  @apply(--layout-flex);
  @apply(--layout-horizontal);
}
.flex {
  @apply(--layout-flex);
}
...
<div class="h-flex">
  <div style="width:20px; background-color: green;">
    ...
  </div>
  <div class="h-flex"><!-- this div isn't needed -->
    <paper-textarea class="flex" label="autoresizing textarea input"></paper-textarea>
  </div>
</div>
```

**Comment by lu2** [comment]
@robrez thanks for the code! The variant without div fixed the overflow issue in my project:
````html
<link rel="import" href="../../iron-flex-layout/iron-flex-layout.html">
...
.h-flex {
  @apply(--layout-flex);
  @apply(--layout-horizontal);
}
.flex {
  @apply(--layout-flex);
}
...
<div class="h-flex">
  <div style="width:20px; background-color: blue;">
    ...
  </div>
    <paper-textarea class="flex" label="autoresizing textarea input"></paper-textarea>
</div>
````
Strange CSS world... Thank you very much again.
