### ISSUE TITLE
Paper-input need a double click in IE (?)

### ISSUE THREAD

**Issue by JustinCase1089** [PolymerElements/paper-input#215]
Hi

When I do this:

    <!doctype html>
    <html>
    <head>
        <script src='bower_components/webcomponentsjs/webcomponents.js'></script>
        <link rel='import' href='bower_components/polymer/polymer.html'>
        <link rel='import' href='bower_components/paper-dialog/paper-dialog.html'>
        <link rel='import' href='bower_components/paper-input/paper-input.html'>
    </head>
    <body unresolved>
        <paper-input></paper-input>
        <paper-dialog style='width:100px;height:100px' opened>
        </paper-dialog>
    </body>

Then the paper-input does not get focus immediately when clicked in IE 11. I need to click it some times before the cursor appears. 

If I remove the 

    <paper-dialog style='width:100px;height:100px' opened>
    </paper-dialog>

From the page, then the paper-input receives focus immediately. 

What could be the issue

Thanks

**Comment by JustinCase1089** [comment]
@notwaldorf ..... any chance you could have a quick look at this one?
I have several sites where IE users are met by a login dialog giving a rather annoying user experience.
Thanks :-)

**Comment by notwaldorf** [comment]
Using the latest dependencies of everything, I tried this in IE10 and IE11, and I can't repro it (http://jsbin.com/gukipo/edit?html,output). 

Can do you do `bower cache clean && bower install` and see if that fixes it? Maybe you have some older versions of the elements.

**Comment by JustinCase1089** [comment]
The problem seems to be when using 
<script src="webcomponentsjs/webcomponents.js"></script>
instead of 
<script src="webcomponentsjs/webcomponents-lite.js"></script>
I am not sure if this makes it a bug and I am not sure what consequences it has if I use -lite instead of "fat" ... is there anywhere where I can find out?

**Comment by JustinCase1089** [comment]
@notwaldorf, if I use the lite version, then the example you have made does not work at all after vulcanization. That's why right now I would need the fat version.

**Comment by JustinCase1089** [comment]
Any news on this one? ... I got another site now where I am suffering from the same issue :-(

**Comment by notwaldorf** [comment]
@JustinCase1089 Are you sure you're vulcanizing everything correctly? You should be using `webcomponents-lite.js`, since that's the better and faster polyfill.

**Comment by JustinCase1089** [comment]
@notwaldorf thanks a million for getting back to me :-). I am doing 
vulcanize --inline-scripts --inline-css
using v 1.14.0, which is the latest
Alright, I have so far been using webcomponents.js. not lite as I have had issues getting it to work correctly in IE.
p.s. if you are into beer, you should visit taphouse in Copenhagen while you are here. It's a very nice place ;-)

**Comment by JustinCase1089** [comment]
@notwaldorf it does not seem like the problem getting a vulcanized lite to work in IE sees that much attention from @azakus at the moment, so I still have a bet on you looking into getting the paper-input to work in IE :-) I really hope you can help

**Comment by JustinCase1089** [comment]
Vulcanize of lite in IE has been fixed in the latest version of IE, so therefore it is not critical for me to have this issue fixed. You can close it unless you still want to have a look at it :-)

**Comment by notwaldorf** [comment]
Closing, then!
