### ISSUE TITLE
Paper-input bug in firefox

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-input#217]
_From @NitroBAY on October 26, 2015 1:29_

Bug with paper-input in last version of firefox (and I don't even dare to talk about IE :-1: I'm doubt about the capocity of Polymer is able to make real project) 
CHROME
![chrome](https://cloud.githubusercontent.com/assets/9869317/10719456/519d519c-7b89-11e5-9a1a-7cdc787298da.png)
FIREFOX
![firefox](https://cloud.githubusercontent.com/assets/9869317/10719457/5482e840-7b89-11e5-8087-32fd2cd1b46c.png)
Here's why it's buggy : 
![bug](https://cloud.githubusercontent.com/assets/9869317/10719462/68a6f762-7b89-11e5-831f-476fa75ce8c6.png)
BTW in chrome autocomplete="off" don't work in chrome neither the way to remove this horrible yellow !! Is that relative to Chrome or .... once again to "Polymer"

_Copied from original issue: Polymer/polymer#2624_

**Comment by notwaldorf** [comment]
Do you have any custom styles that might be getting inherited? Are you importing `paper-input.html` correctly? Is this in a form? How are you forcing it to autocomplete?

Here is a jsbin that has two paper-inputs, and I've tried to style them like yours: http://jsbin.com/yibividesa/1/edit?html,output

This is what it looks in firefox:
<img width="334" alt="screen shot 2015-10-26 at 3 33 14 pm" src="https://cloud.githubusercontent.com/assets/1369170/10744400/e92c7cfa-7bf6-11e5-9671-579db592eb1c.png">
 
Could you provide a snippet of your code to look at? There isn't much to go on here unless we can look at how you're using this exactly...:(

**Comment by NitroBAY** [comment]
css : 

<pre>
<dom-module id="style_home_starter">
  <template>
    <style>

:root
{
  --paper-input-container-input-color: white;
}
.title_logo
{
	color: white;
	margin-top: ;
	margin-left: 70px;
	font-family: 'Miltonian', cursive;
	font-size: 30px;
}
.login
{
	margin-left: 20px;
	display: inline-block;
}
paper-dropdown-menu{
--paper-input-container-underline: { visibility:hidden; }
}
paper-input{
--paper-input-container-underline: { background:white; }
--paper-input-container-label: { color: #fefcfb;}
padding-left : 15px;
width : 150px;
}
paper-input, form
{
	display: inline-block;
}
paper-dropdown-menu
{
	width: 42px;
	color: white;
}
.paper_input_div
{
	display: inline-block;
}
.check_icon
{
	background: transparent;
	color: #FF4081;
	display: inline-block;
}
paper-checkbox
{
	--paper-checkbox-unchecked-color:white;
	--paper-checkbox-label-color:white;
	--paper-checkbox-label-spacing: 4px;
	margin-left: 10px;
	margin-right: 10px;
}
@media screen and (min-width: 1000px)
{
	paper-input
	{
		width: 230px;
	}
}
@media screen and (max-width:830px) {
	.title_logo
	{
		font-size: 23px;
		margin-left: 0px;
	}
	.icon
	{
		display: none;
	}
	.login
	{
		margin-left: 5px;
	}
}
@media screen and (max-width:725px) {
	.title_logo
	{
		top: 15px;
	}
	.icon
	{
		display: none;
	}
	.login
	{
		margin-left: 5px;
	}
}

@media screen and (max-width:640px) {
	.login, paper-input, .check_icon, paper-checkbox
	{
		display: none;
	}
	.title_logo
	{
		font-size: 30px;
	}
}

    </style> 
  </template>
</dom-module>

</pre>

**Comment by NitroBAY** [comment]
<pre>
<dom-module id="form">
<div class="global_login">
    <form accept-charset="UTF-8" method="post" action="{{ url('/auth/login') }}" >
    	{!! csrf_field() !!}	
    	<input style="display:none">
		<input type="password" style="display:none">
    	<div class="paper_input_div">
    		<input type="hidden" name="email" value="@{{email}}">
    		<paper-input label="{{trans('home.login_label')}}" name="email" no-label-float></paper-input>
    	</div>
     	<div class="paper_input_div">
    		<input type="hidden" name="password" value="@{{pass}}">
    		<paper-input label="{{trans('home.pass_label')}}" type="password" name="password" no-label-float></paper-input>
    	</div>
   		<paper-checkbox name="remember">{{trans('home.stay_loged')}}</paper-checkbox>
		<paper-fab icon="check" class="check_icon" mini onclick="submitForm()"></paper-fab>
	</form>	
</div>
</dom-module>
</pre>

**Comment by notwaldorf** [comment]
Ah, I understand now. The problem is that the span and the inputs are misaligned. Looking into it!

**Comment by notwaldorf** [comment]
This is very weird. Do you know what version of `paper-input` this used to work? There's nothing in the styles that implies this should work out of the box, and the fact that it works in Chrome is a coincidence (we are not trying to do that on purpose)

**Comment by notwaldorf** [comment]
@NitroBAY I have a workaround for you (updated jsbin: http://jsbin.com/zonisifigi/edit?html,output). First of all, you need to wrap all your inputs in a flex box, so that you can actually specify how they should be vertically aligned:
```css
.container {
    @apply(--layout-flex);
    @apply(--layout-horizontal);
  }
```

Then, you need to style your label (I wrapped the `@{!! csrf_field() !!}` bit in a span), and give it the same style as the input label:
```css
.label {
    @apply(--paper-font-subhead); /* this is the same font the paper-input label uses */
    padding-top: 10px;                     /* so that they line up */ 
}
```
(see the jsbin for more details).

I don't see why this should work out of the box -- you're basically expecting an unstyled span to perfectly align with the label of a completely, unrelated element :(

Does this work for you?

**Comment by NitroBAY** [comment]
Ah, I understand now. The problem is that the span and the inputs are misaligned. Looking into it! 
.... I don't understand 

I use last version of paper-input I think (composer update)

 There's nothing in the styles that implies this should work out of the box, and the fact that it works in Chrome is a coincidence (we are not trying to do that on purpose)
What??? Paper-input isn't supposed to work without more configuration?? I really don't understand what you're talking about

**Comment by notwaldorf** [comment]
Yeah, exactly; the `.label` class (you can rename it to anything you want) matches the `paper-input`'s label style (the `@apply(--paper-font-subhead)` part), and also adds a padding so that the text lines up. 

Glad this was sorted!

**Comment by NitroBAY** [comment]
But paper-checkbox isn't aligned tough I included in my container :( :sob:

**Comment by notwaldorf** [comment]
You need to do a similar trick like you did with the `.label` class for `paper-checkbox`.

The container is just a flex container. It can put everything at the top, or at the bottom, or in the center. All the elements you are adding to the container are not of the same height, so you have to do this custom styling yourself.

**Comment by NitroBAY** [comment]
YEAH U rock I just add paper-checkbox and all is aligned 
THANKKKKKKKKKKKKKKKS

**Comment by NitroBAY** [comment]
When I remove the no-label-float all is unaligned again. I'm not sure to had undertsood what you said about .label as you said that I can rename it but I've no class with label
