### ISSUE TITLE
Recent update to this element forces Polymer 1.2

### ISSUE THREAD

**Issue by lbustelo** [PolymerElements/paper-input#223]

**Comment by lbustelo** [comment]
It is not clear to me what is the expectation of downstream projects that may indirectly be depending on this element that it is now coded against Polymer 1.2. I think there needs to be contract around what version portion is updated and move away from using ^ in bower.json. 

Our project (https://github.com/jupyter-incubator/declarativewidgets) depends on Polymer 1.1.x and we are not ready or need to move. We are indirectly bringing this element and causes breaks.

**Comment by notwaldorf** [comment]
The idea is that if you want to update an element, you need to update all of its dependencies anyway. You would not be able to just bump `paper-input` up and none of its dependencies -- that would be a nightmare from a maintenance perspective, and this isn't something we can support at the moment. This is why `^` in bower works -- we updated it to match the new Polymer style recommendations, and along with it, we updated the Polymer version it depends on.

/cc @cdata @azakus @rictic for possibly better details

**Comment by lbustelo** [comment]
Quick thought, by if you are going to use ^ (and when I say you I really mean all polymer elements) then when you require a new version of polymer that breaks backwards, then you update the major version. I actually suggest using ~. 

Gino B.

**Comment by azakus** [comment]
I'm not seeing where this element, or any of its dependencies require Polymer 1.2.0.

**Comment by notwaldorf** [comment]
Just to clarify, do you mean that the last paper-input release should have bumped the polymer dependency to 1.2.0? Because with that I agree, and I will bump it in 10 minutes (as soon as I'm on less spotty wifi). It was a oversight on my end.

**Comment by notwaldorf** [comment]
@lbustelo Done! Updated the Polymer version is bower, and cut a new release. Sorry about that!

**Comment by lbustelo** [comment]
@azakus

The error I get points to https://github.com/PolymerElements/paper-input/blob/master/paper-input-container.html#L461

My guess is that the method observeNodes() is not in Polymer 1.1.x. 

@notwaldorf what I was trying to say was that if we you move to require a bump in version of Polymer, then you need to make a more aggressive bump on your version basically because of the use of ^. So for this element, I would have taken it to a 2.x version.

**Comment by notwaldorf** [comment]
It was a minor bump in Polymer, which is a minor, not a major bump for an element. Major bumps represent breaking changes, which this was not.

**Comment by rictic** [comment]
I think what @lbustelo is saying is that if this element requires at least Polymer v1.2.0 to work, then in the bower dependencies it needs to say that. As someone who's trying to teach a robot to reason through our dependencies right now, that seems reasonable to me.

i.e. PR #285

**Comment by notwaldorf** [comment]
Oh, sure. I even said I'd bump it and didn't. Good job, past monica.
