### ISSUE TITLE
documentation and demos don't work for me with prefix

### ISSUE THREAD

**Issue by arpheno** [PolymerElements/paper-input#232]
When I use  as found in the documentation:

    <paper-input label="total">
      <div prefix>$</div>
      <paper-icon-button suffix icon="clear"></paper-icon-button>
    </paper-input>

I cannot type anything in the input field.

The solution is to use:

      <span prefix>$</span>

My version of paper-input:

    vagrant@ubuntu-14:/vagrantbower install --save PolymerElements/paper-input
    bower paper-input#*             cached git://github.com/PolymerElements/paper-input.git#1.0.18
    bower paper-input#*           validate 1.0.18 against git://github.com/PolymerElements/paper-input.git#*

**Comment by notwaldorf** [comment]
Here is a JSBin that uses your example, and seems to work fine: http://jsbin.com/wuvaji/edit?html,output
Is it a browser specific problem?

**Comment by notwaldorf** [comment]
Closing, since there are no repro steps.
