### ISSUE TITLE
Split PaperInputBehavior in two behaviors

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-input#233]
I think that we can split the [PaperInputBehavior](https://elements.polymer-project.org/elements/paper-input?active=Polymer.PaperInputBehavior) in two behaviors:
- **PaperInputBehavior**: `alwaysFloatLabel`, `inputElement`, `label`, `noLabelFloat`...
- **IronInputBehavior**(?): `accept`, `allowedPattern`, `autocapitalize`, `autocomplete`, `autocorrect`, `autofocus`, `autosave`, `inputmode`, `invalid`, `list`, `max`, `maxlength`, `min`, `minlength`, `multiple`, `name`, `pattern`, `placeholder`, `preventInvalidInput`, `readonly`, `required`, `results`, `size`, `step`, `type`, `value`...

In this way, we can re-use the **IronInputBehavior**(?) in other elements. What do you think? :blush:

**Edited** to add the PR #237 reference.

cc @notwaldorf @cdata

**Comment by abdonrd** [comment]
And maybe reorder the behaviors something like this:

**paper-input.html**

```
behaviors: [
  Polymer.PaperInputBehavior
]
```

**paper-input-behavior.html**

```
behaviors: [
  Polymer.IronControlState,
  Polymer.IronFormElementBehavior,
  Polymer.IronInputBehavior(?),        <== This is the new behavior.
  Polymer.PaperInputBehaviorImpl
]
```

**Comment by notwaldorf** [comment]
Oh, I think that would be neat! IronInputBehaviour would just have all the input properties, right?

**Comment by abdonrd** [comment]
Exactly! :rocket:

**Comment by abdonrd** [comment]
And maybe we use other behaviors like [IronRangeBehavior](https://elements.polymer-project.org/elements/iron-range-behavior?active=Polymer.IronRangeBehavior), right?

**Comment by notwaldorf** [comment]
Hmmmm, that doesn't really have anything to do with input, does it? It's a
separate element

**Comment by abdonrd** [comment]
Hmm, the [PaperInputBehavior](https://elements.polymer-project.org/elements/paper-input?active=Polymer.PaperInputBehavior) has the properties:
- `invalid`, `validator`... [IronValidatableBehavior](https://elements.polymer-project.org/elements/iron-validatable-behavior) also has.
- `max`, `min`, `step`... [IronRangeBehavior](https://elements.polymer-project.org/elements/iron-range-behavior?active=Polymer.IronRangeBehavior) also has.

Maybe we can reuse something.

**Comment by abdonrd** [comment]
Something like #237? :)

**Comment by notwaldorf** [comment]
Argh, maybe IronInput isn't the right name afterall. The problem is that I would expect `iron-input` to use IronInputBehaviour. This is more the `InputBitOfPaperInputBehaviour` behaviour, and I don't have a good name for this.

Let me ask @cdata who is much better at naming things (I am terrible).

**Comment by abdonrd** [comment]
Okey! We wait! :blush:

**Comment by abdonrd** [comment]
Any news? :see_no_evil:

**Comment by MeTaNoV** [comment]
+1 for this one!

**Comment by abdonrd** [comment]
Soft reminder to @notwaldorf and @cdata. :blush:

**Comment by abdonrd** [comment]
Any news about this? I rebased the https://github.com/PolymerElements/paper-input/pull/237. :)

**Comment by notwaldorf** [comment]
I am tempted to leave this alone for a bit. `paper-input` the element is in a bad shape -- it's pretty expensive compared to other elements, and it has a bunch of antipatterns we don't like (such as trying to do everything with just a `type` attribute) and contribute to the badness. I'm working on a new element, `paper-text-field`, which is the v2.0 of this element. It's currently private (but very close to becoming public). It will be experimental for a while, so we can play a little bit more with the API (and it does a split similar to this).

**Comment by abdonrd** [comment]
Interesting! Thanks for the explication @notwaldorf! :)

**Comment by notwaldorf** [comment]
As an update, PolymerElements/paper-text-field is the element I mentioned. It's very in progress and experimental, so don't expect it to be a 1-1 match for `paper-input` for a while :)

**Comment by abdonrd** [comment]
Thanks for the notice @notwaldorf! :)

**Comment by abdonrd** [comment]
As far as I know, the Polymer Elements are not going to continue developing. So I close this issue.
