### ISSUE TITLE
value of paper-textarea inside native form ignored when submitted

### ISSUE THREAD

**Issue by jab** [PolymerElements/paper-input#239]
Please see http://jsbin.com/dequhi/edit?html,output for a minimal reproduction.

Notice that both the paper-input and the paper-textarea have a name and a value, but when the form is submitted, jsbin reports that only the paper-input's form data was submitted:
```json
"form": {
    "paper-input": "paper input works"
}
```
while the paper-textarea's form data was ignored. It looks like paper-textarea is neglecting to pass on the `name` attribute it was created with to its contained native textarea.

**Comment by jab** [comment]
It looks like this issue is caused by an upstream bug in iron-autogrow-textarea. Submitted a PR with a fix: PolymerElements/iron-autogrow-textarea#55

**Comment by notwaldorf** [comment]
Please see https://github.com/PolymerElements/iron-autogrow-textarea/issues/33 for a discussion. `paper-textarea`  is not supported in native forms; you need to use an `iron-form` instead. `paper-input` is the *only* element that works by default in a native form.
