### ISSUE TITLE
Programatically changing iron-input does not reflect back to paper-input

### ISSUE THREAD

**Issue by srikkbhat** [PolymerElements/paper-input#245]
1. Listen for `on-tap` on paper-input.
2. Set a value programatically to event.target. event.target is iron-input.
3. The value is visible on the input field, however it is not reflected back to paper-input.value.

I looked into iron-input code and it listens to bindValue. I modified the code to set the bindValue rather than value. But the question is should it also listen to changes to value and set it to bindValue.

plunker: http://plnkr.co/edit/mckRA9E4LlsqAyoPabNS?p=preview

**Comment by notwaldorf** [comment]
The problem is that it you programmatically change `value` on an `<input>`, this does not fire an event, so nobody is notified. This is why you need to change `bindValue`, which notifies anybody that cares (i.e. `paper-input`)
