### ISSUE TITLE
FireFox: bound property on disabled fields - label issue 

### ISSUE THREAD

**Issue by manfield** [PolymerElements/paper-input#246]
We experienced this issue:

If paper-input value is bound to a property, like that

`<paper-input class="flex" disabled label="Password" value="{{user.passwordShow}}" ></paper-input>`

label overlays value on Firefox (i.e: http://screencast.com/t/A9iZT5wIc5).

It does not happen if paper-input is not disabled.
It does not happen if value is a static text (instead of a bound value).

**Comment by notwaldorf** [comment]
This is caused by https://github.com/PolymerElements/iron-input/issues/47. Will be fixing it there this week
