### ISSUE TITLE
paper-input can overflow container during css transition.

### ISSUE THREAD

**Issue by coreyfarrell** [PolymerElements/paper-input#247]
The css transition for label-is-floating is 0.25 seconds, where the element is scaled to 75%.  The width becomes 133% to compensate for this and make the label keep using 100% actual width.  Unfortunately the width is applied immediately and it takes 0.25 seconds for the scale to get to 75%.  During this 0.25 seconds the label causes the paper-input to overflow, creating scroll-bars.

I haven't found a way in CSS to animate changing the width, so in my own project I've set the transition to 0 seconds.

**Comment by ianbitts** [comment]
So, fair admission, I don't really understand what I'm doing, but i was able to stop the scrollbars from appearing during the animation by applying the following style using CSS mixins.

```paper-input { 
  --paper-input-container-label-focus: {
    width: 100%;
  };
}```

**Comment by notwaldorf** [comment]
I think this may have been fixed by https://github.com/PolymerElements/paper-input/pull/294. I haven't tagged a release for it yet, but the master branch should ideally not have this issue anymore.

**Comment by notwaldorf** [comment]
Closing (should be fixed as mentioned previously)
