### ISSUE TITLE
Incorrect "label" property description for paper-input-behavior

### ISSUE THREAD

**Issue by MeTaNoV** [PolymerElements/paper-input#249]
The description in question is:
```
      /**
       * The label for this input. Bind this to `<paper-input-container>`'s `label` property.
       */
      label: {
        type: String
      },
```
however, one should bind this to `<label>` content and (optionally?) `hidden` property, like done in the implementation of `<paper-input>` or `<gold-email-input>`:

```
...
    <paper-input-container no-label-float="[[noLabelFloat]]"...

      <content select="[prefix]"></content>

      <label hidden$="[[!label]]">[[label]]</label>

      <input is="iron-input" id="input"...
...
```

More of an additional question, `<gold-email-input>` is redefining the `label` property and set a default value. Would it be correct to set the default in `ready` function and therefore, not redefining the property at all?

**Comment by notwaldorf** [comment]
`gold-email-input` isn't redefining the property, it's just setting the default value on it. I think Polymer does magic and if the property is already defined, it just adds the new fields to it (in this case the default value)

**Comment by MeTaNoV** [comment]
done, thanks! :)
