### ISSUE TITLE
Mixin "--paper-input-container-input" not working

### ISSUE THREAD

**Issue by Talionar** [PolymerElements/paper-input#251]
--paper-input-container-input in "paper-input-container-input.html" string 254.

If I renaming it to something else, ex. "--paper-input-container-inputs" all work perfect. Maybe too much "input" words in this mixin?

**Comment by notwaldorf** [comment]
Here is a jsbin using it: http://jsbin.com/wosenub/edit?html,output

What's probably happening is that you were trying to use properties (like `color`) that are probably overwriten by a different selector.
