### ISSUE TITLE
type=number don't work in iOS 9.1 with cordova project

### ISSUE THREAD

**Issue by horochovec** [PolymerElements/paper-input#252]
Exemple:

<paper-input id="codigo" type="number"></paper-input>

This input type don't show the correct keyboard when I build a App for iOS, at Android, everything works fine.

I'm using cordova 5.x

**Comment by notwaldorf** [comment]
Are you looking for the digits-only keyboard? Because I think that comes from type=tel not number.

**Comment by horochovec** [comment]
@notwaldorf Thanks, to work at IOS need to change to "type=tel" :)
