### ISSUE TITLE
Long labels are terminated with an ellipsis instead of wrapping; Impairs responsive design

### ISSUE THREAD

**Issue by miztroh** [PolymerElements/paper-input#254]
The ellipsis of overflowed text in labels makes responsive design difficult (e.g. How can mobile website users answer questions intelligently if the questions are cut off?)

Wide layout:
![wide](https://cloud.githubusercontent.com/assets/2515209/11197295/30191ef2-8c82-11e5-843f-71c974773489.png)

Narrow layout (actual):
![narrow](https://cloud.githubusercontent.com/assets/2515209/11197297/32ef8ada-8c82-11e5-8fc4-a940f74ba81c.png)

Narrow layout (expected):
![ideal](https://cloud.githubusercontent.com/assets/2515209/11197368/9b12a228-8c82-11e5-864d-828fa61a5e7a.png)

**Comment by notwaldorf** [comment]
The problem with wrapping the label in this element is that:
- you either pre-compute the final, wrapped height before actually showing the label, in which case in 
the non-floated-label case, different inputs will be of different heights
- you wrap the text after the label has floated, in which case all of your layout will jump around.

Neither of these is good, in my opinion, and I don't think paper-input should do that. Labels should be fairly short and descriptive (think of the `placeholder` attribute of a native input, for example)

However, to fix your use case, I suggest using no label attribute for your input (as well as the `no-label-float` attribute), and using a styled `iron-label` (which gives you accessibility features) that you can apply the proper styling to. Here is an example for that: http://jsbin.com/qacidud/edit?html,output

I will also see if I can send a PR to show the full text of the label in a `title` attribute, when mousing over the truncated label.

**Comment by miztroh** [comment]
I had already begun to work around this with separate labels.  I understand that as placeholder text, space is limited.  However, for my use case I set all inputs (``paper-input``, ``paper-textarea``, ``paper-dropdown``) to ``always-float-label``.  I use the floating labels to show questions the user needs to answer to submit the form.  Most questions are shorter, but a few cannot be.  It would be nice if wrapping could be at least be an option (or perhaps automatic if ``always-float-label`` is ``true``).

**Comment by notwaldorf** [comment]
Ah, you can do this yourself with a mixin:
```
paper-input {
  width: 100px;
    --paper-input-container-label: {
        word-wrap: break-word;
        white-space: normal;
    }
}
```

Here's a jsbin with an example: http://jsbin.com/mibere/edit?html,output

**Comment by javamaniac** [comment]
I have the same problem with the error-message. The message is cropped.
@notwaldorf is it possible that both jsbin examples don't work anymore?

**Comment by notwaldorf** [comment]
Yeah, I think the JsBin has Polymer 1 code, but polygit is loading Polymer 2 so it doesn't work (the `custom-style` element is missing). Here's an updated Polymer 2 example: http://jsbin.com/fugaci/edit?html,output
