### ISSUE TITLE
Issue from 1.0.18 to 1.1.0

### ISSUE THREAD

**Issue by manfield** [PolymerElements/paper-input#257]
We're experiencing an issue substituting paper-input from version 1.0.18 to 1.1.0.
This page changes from:
<img width="1336" alt="meta_ok" src="https://cloud.githubusercontent.com/assets/397671/11300025/f4175600-8f8b-11e5-816c-bf5e0be1f845.png">
To:
<img width="1339" alt="meta_ko" src="https://cloud.githubusercontent.com/assets/397671/11300039/00f02096-8f8c-11e5-9617-7a9ac2e4e58a.png">

The strange thing is that even if I remove paper-inputs in page, the page results broken anyway.
Probably, importing paper-input component, introduces some piece of code that makes it happen.

This is what I mean:

<img width="1336" alt="meta_ko_2" src="https://cloud.githubusercontent.com/assets/397671/11300078/466dcc68-8f8c-11e5-9442-944bbb8b4fef.png">

**Comment by notwaldorf** [comment]
Pre 1.10, paper-input was importing all of paper-styles.html, which was unfortunately importing /deep/ styling for the flex layout classes in iron-flex-layout (thus making them automagically available anywhere in your app). What's most likely happening is that your page was using one of these classes, and not explicitly importing them. I would recommend tracking these down, and using one of the mixins in iron-flex-layout to explicitly style the element in question

**Comment by notwaldorf** [comment]
By the way, I would also recommend using the mixins and not the classes import of iron-flex-layout, since the classes import also uses /deep/, which is deprecated, and will be removed until he future

**Comment by manfield** [comment]
Thanks a lot, I will try with mixins. I've also to refactor many parts before total deprecation of /deep/.
