### ISSUE TITLE
validation inside iron-form stops working if readonly attribute of paper-input is set

### ISSUE THREAD

**Issue by Qvatra** [PolymerElements/paper-input#265]
I have iron-form and paper-input type='text' with value binding, required attribute and error-message attribute.
```
<form is="iron-form" id="form" method="post" action="/form/handler">
   <paper-input type="text" label="[[part.label]]" value="[[part.value]]" name="[[part.key]]" required error-message="Invalid input!"></paper-input>
</form>
```

Validation works just fine and I see my error-message BUT if I set readonly attribute to my paper-input validation stop working.

```
<form is="iron-form" id="form" method="post" action="/form/handler">
   <paper-input type="text" readonly label="[[part.label]]" value="[[part.value]]" name="[[part.key]]" required error-message="Invalid input!"></paper-input>
</form>
```

Logically speaking this is a bug because required attribute is still set but no validation happens.

I still want validation to work even with readonly attribute.. How to do that?

**Comment by MeTaNoV** [comment]
This is by design: [HTML 5 Spec](http://www.w3.org/TR/html5/forms.html#attr-input-readonly)

> **Constraint validation**: If the readonly attribute is specified on an input element, the element is barred from constraint validation.

**Comment by Qvatra** [comment]
@MeTaNoV, hm.. too bad. do you know by any chance a workaround for that?

I need an element that looks like paper-input and not editable by user.. only via value binding

**Comment by MeTaNoV** [comment]
As a workaround, on value change, you can try to reapply the old value.

**Comment by Qvatra** [comment]
@MeTaNoV, but I want to be able to change value via data-binding, that means that ''on-value-change'' event would be called also...

**Comment by MeTaNoV** [comment]
sorry, I meant onKeyPress (and onInput?)

**Comment by Qvatra** [comment]
thx, will try that

**Comment by Qvatra** [comment]
```
on-keydown="_manualInput"

_manualInput(e, d) {
       e.preventDefault()
}
```

this did the trick. thx
