### ISSUE TITLE
input background line doesn't match spec

### ISSUE THREAD

**Issue by joeyperson** [PolymerElements/paper-input#272]
Is there a reason why it is a lot darker?
https://goo.gl/photos/srxkTvYAT5cNBxC3A

 Is this to improve usability? The stickersheets show them to be 12% black, which looks to match the Google spec.

**Comment by notwaldorf** [comment]
Yes, I think so. We've had to darken some elements, since the original MD spec had low contrast.

**Comment by notwaldorf** [comment]
Here is the original issue: https://github.com/PolymerElements/paper-input/issues/5
