### ISSUE TITLE
Add the new required text fields (December 2015 release of the material design spec)

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-input#274]
The December 2015 release of the material design spec includes:
- Text fields adds guidance on required text fields:
  https://www.google.com/design/spec/components/text-fields.html#text-fields-required-fields

**Comment by MeTaNoV** [comment]
Since I would like to have this feature, I just made a PR for it!

**Comment by florent1933** [comment]
@notwaldorf: Will it be implemented for the V1? and for the V2?

**Comment by MeTaNoV** [comment]
@florent1933 let's cross finger for 2.0! :)

**Comment by florent1933** [comment]
:crossed_fingers: Fingers crossed !

**Comment by abdonrd** [comment]
As far as I know, the Polymer Elements are not going to continue developing. So I close this issue.
