### ISSUE TITLE
Sizing issues in ie

### ISSUE THREAD

**Issue by robrez** [PolymerElements/paper-input#275]
If a paper-input is used inside of a horizontal flex container, it's size is teeny-tiny...

eg:
```
<div class="layout horizontal justified">
  <paper-input label="one"></paper-input>
  <paper-input label="two"></paper-input>
</div>
```

The issue can be seen via this jsbin --
http://jsbin.com/necala/edit?html,output

The same general issue has been documented in a couple of other repos --
here...
https://github.com/PolymerElements/iron-flex-layout/pull/9
and here...
https://github.com/PolymerElements/paper-tabs/issues/29

**Comment by notwaldorf** [comment]
Fixes by #276
