### ISSUE TITLE
Date input not working properly

### ISSUE THREAD

**Issue by aabluedragon** [PolymerElements/paper-input#280]
In Safari, no date formatting.
In Chrome, the label is overlapping date value unless a year is given

http://jsbin.com/lurefa/4/edit?html,output

**Comment by notwaldorf** [comment]
Whenever using types that use custom styling, it's recommended to either use a placeholder and not the label, or us `always-float-label` (see: https://github.com/PolymerElements/paper-input/blob/01fd30bb3e63c610219c4c9b0a2fa873fe6dfea9/paper-input.html#L41 in the docs)

Secondly `<input type="date">` is not implemented in Safari (http://caniuse.com/#search=date), and `paper-input` is just a wrapper around it, so it won't work there either.
