### ISSUE TITLE
Validating IP Addresses

### ISSUE THREAD

**Issue by rogerta** [PolymerElements/paper-input#287]
I am using a `<paper-input>` to enter IP addresses, and using a pattern to validate the data.  The elements are instantiated as follows:

          <paper-input label="LAN IP Address" id="myid" required
             ip-address-field auto-validate value="{{lanIPAddress}}"
             error-message="Must be a valid IP address">
          </paper-input>

and in ready():
```
    var IP_PATTERN = '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$';

    ready: function() {
      var nodes = this.querySelectorAll('paper-input[ip-address-field]');
      for (var i = 0; i < nodes.length; ++i) {
        var item = nodes[i];
        item.pattern = IP_PATTERN;
      }
  },
```

The elements accept the following *invalid* strings as valid:
```
192.168.42
192.168
192.16842
19216842
```
The elements correctly determine the following strings as invalid:
```
192.168.42.
192.168.
192.
192
```
The elements seem to correctly handle valid strings.

I have checked the regex filter with https://regex101.com/#javascript and it seems to be correct.  I have also used the chrome javascript console to test the expression:
```
/^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/.test('192.168.42')
false
/^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/.test('192.168')
false
/^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/.test('192.16842')
false
/^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/.test('19216842')
false
```

I am using the following:

```
In bower.json: "PolymerElements/paper-input#~1.0.11"

Browser 1: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2593.0 Safari/537.36
Browser 2: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.48 Safari/537.36
```

It would also make my day if @notwaldorf fixed this for me ;-)

**Comment by notwaldorf** [comment]
Hiya Roger! I'll take a look :)

**Comment by notwaldorf** [comment]
@rogerta I put together a jsbin here (http://jsbin.com/hemulu/edit?html,output) covering all the cases, both with a native input, and with a `paper-input`. It seems that when you add the `pattern` attribute dynamically, you need to provide it as a regex (`"/your-pattern/"`), rather as the plain string alone.

I've double checked and making all the patterns as (`"/your-pattern/"`) works in all cases. I'm not sure why setting it in html (rather than dynamically) is more forgiving and doesn't require the leading and trailing `/`, but I'm suspicious there's dark `<input>` magic at work.

Let me know if this works for you!

**Comment by rogerta** [comment]
Thanks fore investigating Monica, I totally missed the subtlety there.  I'm
off for the rest of the year so likely won't be able to check it out until
January.  Have a great holiday and happy new year!

=================================================
Roger Tawa
http://tawacentral.net/
[When you stop, you're done.]

**Comment by notwaldorf** [comment]
Going to close this. As discussed offline, there's something weird going on with this particular regex when applied dynamically, and it happens for the plain native input case as well, which means it's not a paper-input bug (full testing jsbin: http://jsbin.com/hemulu/edit?html,output).
