### ISSUE TITLE
Styling paper-input, paper-textarea directly

### ISSUE THREAD

**Issue by devinivy** [PolymerElements/paper-input#290]
I see how one can style these inputs using paper-input-container, but it seems that paper-input and paper-textarea do not contain any mixins to style their internal paper-input-containers.  Unless theres a Polymer pattern I'm missing, that makes it seem like there's no way to style the paper-input and paper-textarea elements.  Is that right?  Could we possibly add this mixin?

**Comment by notwaldorf** [comment]
Oh, all of the same mixins from paper-input-container apply to paper-input and paper-textarea, since they're all essentially just containers. I can put together an example for you later if it still doesn't work out.

**Comment by devinivy** [comment]
Ah, I thought that the mixins were not automatically inherited (within the shadow dom) from styles on the root element.  Sounds like I had that pretty wrong!  Perhaps it would be worth noting in the docs that paper-input and paper-textarea have the same CSS interface as paper-input-container– there's otherwise no contract with the developer that their CSS mixins wont stop working some day.  I'll try this out tomorrow as let you know how it goes.  Thanks!

**Comment by notwaldorf** [comment]
We have this line in the docs (https://github.com/PolymerElements/paper-input/blob/master/paper-input.html#L59). Should we try to make it more clear?

**Comment by devinivy** [comment]
I saw that.  Maybe?  It is good that the docs address it, but `Polymer.PaperInputContainer` looks like a js object– one that doesn't exist.  Is it a standard way to talk about the element `<paper-input-container>`.  It might be worthwhile to be explicit and say "See `<paper-input-container>` for compatible CSS mixins" or something along those lines.

**Comment by devinivy** [comment]
Works great :) Thanks.  I'm not making a stink about the docs.  I'm not sure if they should be made more clear or if I just overthought them– I'll let you be the judge!
