### ISSUE TITLE
paper-input with type="date" issue

### ISSUE THREAD

**Issue by khoanguyenlio** [PolymerElements/paper-input#291]
I try to use paper-input with type="date" and i got a problem with this:
`<paper-input ngDefaultControl type="date" label="birthday" ></paper-input>`
![typedate](https://cloud.githubusercontent.com/assets/9152575/11970974/d2a58154-a967-11e5-88e3-717ecebec747.png)
and some issue like this
![datepinput](https://cloud.githubusercontent.com/assets/9152575/11970991/25ea8e7c-a968-11e5-9171-cf65e2cfb655.jpg)

**Comment by notwaldorf** [comment]
For now, as described in the docs, you should use the `placeholder` attribute instead of the label: https://github.com/PolymerElements/paper-input/blob/master/paper-input.html#L41

I will do a PR for this soon though, since this issue comes up a lot.

**Comment by khoanguyenlio** [comment]
OK Thanks !
