### ISSUE TITLE
(Angular 2.0.0 beta.0 + Polymer 1.0) paper-input data binding not working on IE11

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-input#298]
_From @ldtung on December 27, 2015 13:51_

I have a paper-input component declared as below, where myField is a field initialized with value="TestValue"

paper-input ngDefaultControl [(ngModel)]="myField" label="my label"

On chrome, it's working fine, "TestValue" is displayed when loading screen.
The two way data binding working fine.
but on IE11, "TestValue" is not displayed. Even if i changed value in paper-input to something else,
the data model is not updated.

I debugged into the code, and see that NG2 has already updated the paper-input's value to "TestValue" when rendering the screen but seems the input inside does not see the same value

Any idea?

_Copied from original issue: Polymer/polymer#3237_

**Comment by notwaldorf** [comment]
@ebidel I don't know anything about angular :/

**Comment by ebidel** [comment]
Maybe @ldtung can give us a reproducible test case.

**Comment by ldtung** [comment]
I knew the reason why, on IE, the Angular application which using Polymer elements must wait until all htmls loaded before booting up.
This solution works for me:
// Remember that we must wait until all HTML links loaded before booting the Angular 2 application.
    // on IE, it's not working without this.
    HTMLImports.whenReady(function () {
        System.import('dist/boot').catch(
           console.log.bind(console)
        );
    });

**Comment by zoechi** [comment]
NgModel also doesn't work with custom Angular components, only with `<input>` AFAIK

**Comment by byavv** [comment]
IE and FireFox don't work well because of their html imports loading algoritm, which differs from Chrome. I dont know, how exactly it works, but this: 
```javascript
// start angular after all polymer html imports are resolved and elements are registered
window.addEventListener('WebComponentsReady', (e) => {
    bootstrap(// <--- Angular2 bootstrap
        App,
        PROVIDERS
    ).then((app) => {
        // do smth with app        
    }, error => console.log(error))
})
```
should help.
It's not very neat, but it works

**Comment by khoanguyenlio** [comment]
you can add ngDefaultControl like this <paper-input ngDefaultControl  ...></...>

**Comment by notwaldorf** [comment]
It looks like a solution has been provided! Please re-open if that's not the case

**Comment by praveenpuglia** [comment]
This does not work for me anymore. I remember using this hack to get it working but with angular 2.1.0 it doesn't work anymore. 
:(
