### ISSUE TITLE
allowed-pattern and auto-validate?

### ISSUE THREAD

**Issue by cpboyd** [PolymerElements/paper-input#302]
I'm aware that I can set ```prevent-invalid-input``` and restrict the input to the ```allowed-pattern```, but is there a reason that ```auto-validate="true"``` doesn't result in the ```allowed-pattern``` being checked if invalid input is allowed.

e.g., I'm using ```allowed-pattern="[0-9]"``` to specify that only numeric values are valid (and state as much in the ```error-message```) but everything still shows as fine with ```auto-validate="true"``` if I enter an 'a' or other non-numeric character.

**Comment by notwaldorf** [comment]
Yeah, we did a bit of cleaning there. `pattern` should be the attribute used for validation, as that's what the native `input` uses. `allowed-pattern` is only used in conjunction with preventing input. Separating these has a bunch of useful reasons: you might want to prevent the user from typing anything but numbers, but a valid entry would have to be at least 5 numbers long, for example.

In your case, I think what you're looking for is:
```
<paper-input allowed-pattern="[0-9]" pattern="[0-9]" auto-validate="true">
```

Like so: http://jsbin.com/vimafu/edit?html,output

**Comment by cpboyd** [comment]
Ah, thanks for the clarification!

**Comment by notwaldorf** [comment]
No worries!
