### ISSUE TITLE
paper-input is blank after navigating out and back on mobile safari

### ISSUE THREAD

**Issue by zboralski** [PolymerElements/paper-input#309]
I have a `paper-input` inside an `iron-form`... everything works everywhere except on mobile safari...

If I navigate outside of my Polymer app and hit the back button. The page appears from the history without being reloaded (on all other user agent it gets a reload)... Everything is displayed correctly except the `paper-input` element which is now blank... its value field is bound to a property `q`. If I open the console in safari from my Mac, I can inspect that the `paper-value` is still set to the right value... but for some reason it doesn't display anymore.  Enabling reflectToAttribute and notify, doesn't seem to help.

**Comment by zboralski** [comment]
Anyone encountered this issue?

**Comment by notwaldorf** [comment]
Would you mind double checking for a native `<input>`, in the same case? It would be great if you could provide a JSBin with repro steps. Here's a sample to get you started: http://jsbin.com/cagaye/edit?html,output

**Comment by zboralski** [comment]
@notwaldorf I've tried with a native input and I have the same problem...

```html
horizontal center-justified layout">
      <input id="input" name="search" value="{{q}}" autocorrect="off" autocomplete="off"
      icon="search" autocapitalize="off" on-button-click="performSearch"></input>
```

As I said it works perfect in any user agent other than iOS's mobile safari... if you navigate away from the page and hit back the value is not set... if you attach to the console from a mac's safari developer menu, you'll notice that the page isn't reloaded. 

I have also tried inside a native form and I get the same issue... Maybe it isn't a paper-input issue but an issue in Polymer...

jsbin doesn't let you submit a form or click on an anchor so I don't see how I can reproduce the issue using jsbin... because you have to navigate out and then hit back...

**Comment by notwaldorf** [comment]
That's weird, maybe there's a problem with mobile safari? If you hit back and the page isn't reloading, that sounds to me like it's a browser bug, not a Polymer bug (especially since you say this works on other browsers). If the page _is_ reloading and the value isn't set, I am worried this is native platform magic (where `form` has special code to do this), which we can't really emulate easily :(

**Comment by zboralski** [comment]
Ok... just did more test and normal safari on my Mac has the same issue. 

Here is a good way to test the issue: 

https://elements.polymer-project.org/browse?q=test

You will see the input field is set to test.

![screen shot 2016-01-29 at 08 22 15](https://cloud.githubusercontent.com/assets/104316/12670572/6e76f8e0-c661-11e5-9f15-1d5b639bcc31.png)

Now open the console and navigate away from the page :

window.location.href = "https://google.com"

Hit the back button .... the value is still set to 'test' as you can see :

![screen shot 2016-01-29 at 08 21 20](https://cloud.githubusercontent.com/assets/104316/12670549/4d3de148-c661-11e5-8f89-283f5568bb79.png)

The input field isn't set.

**Comment by zboralski** [comment]
In my particular case... the input value is bound using {{q}} and when I inspect my elements property q is still set correctly :

```js
$0.q
"test"
```

**Comment by zboralski** [comment]
I think it is a polymer issue... for example on github :

https://github.com/polymer/?utf8=✓&query=test

Hit the pricing link in the bottom right corner... then hit the back button and the input field will still be set to 'test'

**Comment by zboralski** [comment]
I think this is a Polymer issue...
