### ISSUE TITLE
[Paper]-Input hint not turning into label on ChromeBook apps

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-input#31]
[Moved from Polymer/polymer. Quoted issue below.]

Hi,

I tried using the iron-input element [assume meant paper-input] and works fine when packaged as an app .crx on Chrome browser on mac or pc. When the same .crx ported to chromebook the app just loads fine but has following issues
1.The input element's hint turning into label wont just work.
2.If this input element is a part of form, then form submission wont read the values from these elements. 

Attached screenshots from desktop chrome (just works fine) and chromebook (where it wont).

Thanks
Akhash
<br>
<b>On Desktop :</b><br>
![chrome](https://cloud.githubusercontent.com/assets/695965/7739874/bc13c7ce-ff1d-11e4-8674-84e63ba83ec4.png)

<br>
<b>On ChromeBook:</b><br>
![cb_1](https://cloud.githubusercontent.com/assets/695965/7739895/ee2726ac-ff1d-11e4-9a55-0ac41cce7a62.png)
![cb_2](https://cloud.githubusercontent.com/assets/695965/7739896/f25eddf0-ff1d-11e4-8d79-7120611a838d.png)
![cb_3](https://cloud.githubusercontent.com/assets/695965/7739898/f46734f8-ff1d-11e4-9cf1-f00aad89c809.png)

**Comment by alotabits** [comment]
Chrome on Mac has the same issue on version 43.0.2357.73 beta. In the process of working my way around this issue, I found that wrapping a plain input with paper-input-container produces a working input with a hint that becomes a label. Specifying attr-for-value on the container breaks this behavior. Also, on the demo page, you can see that paper-textarea works as expected.

**Comment by frankiefu** [comment]
I can reproduce the issue by running the demo on Chrome Beta.

![screen shot 2015-05-21 at 6 13 51 pm](https://cloud.githubusercontent.com/assets/116360/7762252/84a91b58-ffe6-11e4-9d23-b48aff2ed680.png)

**Comment by morethanreal** [comment]
Might be fixed. I cannot reproduce on Chrome 43. @frankiefu ?

**Comment by alotabits** [comment]
I pulled updates via bower earlier today and checked the demo page. Fixed
on Chrome 43 for OS X.
