### ISSUE TITLE
Maximum call stack size exceeded with paper-dropdown-menu as suffix

### ISSUE THREAD

**Issue by cpboyd** [PolymerElements/paper-input#312]
I was trying to use a paper-dropdown-menu selector for units to use for the input value.
e.g.: mm, cm, m, km

I'm guessing Polymer is calling callbacks for both the dropdown menu and the paper-input, which is leading to this error.

Perhaps the best way to avoid this is to simply position the two elements using CSS.  I just tried this since I've already used ```<div suffix>``` for other static units.

**Comment by notwaldorf** [comment]
I can't seem to repro this: http://jsbin.com/kaxatu/edit?html,console,output. Please re-open if you have a jsbin with a repro case.

**Comment by cpboyd** [comment]
What I get in Chrome when clicking the dropdown menu in your jsbin:

![rangeerror](https://cloud.githubusercontent.com/assets/6323077/12665270/90c0dd4c-c604-11e5-959f-fca7696284e0.png)

Everything works as expected, visually.  I just feel uneasy with the errors.

Notably, I don't get any errors reported in Firefox or Edge.

**Comment by cpboyd** [comment]
@notwaldorf This issue still occurs in Chrome's console with your JsBin.
Note, the errors never appear in JsBin's console.

I think the issue is related to the fact that both ```paper-input``` and ```paper-dropdown-menu``` implement ```IronControlState```.

Most of the errors seem to trace back to ```_focusBlurHandler```:
https://github.com/PolymerElements/iron-behaviors/blob/master/iron-control-state.html#L67

Also, I can't re-open the issue since I'm not a collaborator.

**Comment by cpboyd** [comment]
Actually, I just tried removing IronControlState from paper-dropdown-menu but still had the error.

Perhaps it has more to do with the menu-button making the paper-listbox appear?
(That would explain why the paper-input flashes several times whenever it opens or closes.)

If it's just a paper-listbox, then there's no issue:
http://jsbin.com/nuguxifiru/edit?html,console,output

**Comment by cpboyd** [comment]
I've found the ultimate culprit:
```paper-dropdown-menu``` utilizes a paper-input.

The best solution is to simply define a custom ```paper-menu-button``` that doesn't have a nested paper-input.

**Comment by notwaldorf** [comment]
I think this might actually be related to https://github.com/PolymerElements/paper-input/issues/324. Good to know you found a workaround, though!
