### ISSUE TITLE
Consider creating a password-reveal sub-element?

### ISSUE THREAD

**Issue by vinerz** [PolymerElements/paper-input#316]
Hello everyone! I must say every time that your work is awesome.

Please consider this enhancement for paper-input of type password: Password Revealing

I've made a very crappy implementation of my idea so I can't even consider to make it as a pull request hahaha, but here it goes:

Consider this password input:
![image](https://cloud.githubusercontent.com/assets/1482034/12465200/08cd05ec-bfb4-11e5-9b50-73fe9f79f7a5.png)

I type some secret data to it:

![image](https://cloud.githubusercontent.com/assets/1482034/12465227/28ad5812-bfb4-11e5-9e80-9ca9deabcad9.png)

And finally I can check what I wrote by simply clicking or touching the eye button:

![image](https://cloud.githubusercontent.com/assets/1482034/12465249/44f050a6-bfb4-11e5-9a2b-2b7cef5f6b8d.png)

This suffix would act like the `dialog-dismiss` attribute for paper-dialog.

The final markup would be:

```
<paper-input type="password" label="Password">
    <paper-icon-button suffix password-reveal icon-show="visibility" icon-hide="visibility-off"></paper-icon-button>
</paper-input>
```

**Comment by MeTaNoV** [comment]
good idea to add to my `gold-password-input`, thx! :)

**Comment by vinerz** [comment]
Great idea. This should be a gold element instead of paper-input improvement.
Is your gold element public?

**Comment by MeTaNoV** [comment]
@notwaldorf can answer your question better than me, but I will implement it on my own element since it is plainly relevant! FYI, my element can be found here: https://github.com/MeTaNoV/gold-password-input (among others element I implemented)

**Comment by MeTaNoV** [comment]
@vinerz just finished the implementation: https://github.com/MeTaNoV/gold-password-input/releases/tag/v1.1.0

**Comment by notwaldorf** [comment]
I don't think that we will add this as a feature to `paper-input` proper. `paper-input` is a pretty generic input, and adding an icon that is only used in the case of `type=password` is actually pretty expensive :(

Implementing this yourself is actually pretty easy, though! Here's a jsbin that does this for you, using a `prefix` and 4 lines of code: http://jsbin.com/cawija/edit?html,console. Basically, you just need to toggle between the `text` and `password` and in the input's type.

**Comment by notwaldorf** [comment]
(or you can totally use @MeTaNoV's element if that works for you better! 😊)
