### ISSUE TITLE
Empty input considered valid regardless of minlength

### ISSUE THREAD

**Issue by cpboyd** [PolymerElements/paper-input#332]
As the issue title states, trying to validate an empty paper-input will result in ```true```, even if the paper-input has a minlength.

Example with auto-validate:
http://jsbin.com/yidawicowa/1/edit?html,console,output

Note, if there's any input, (but less than the maxlength) then it turns red.

If there's no input, it turns blue.

**Comment by notwaldorf** [comment]
According to the spec, the `minlength` attribute only kicks in _if_ a value is specified, and does not imply `required`: https://www.w3.org/TR/html5/forms.html#setting-minimum-input-length-requirements:-the-minlength-attribute. Here's a jsbin demonstrating that this also happens with the native `<input>` element: http://jsbin.com/rogeno/edit?html,output

If you want the input to be invalid when nothing has been entered, then you need to also add the `required` attribute.

Hope this helps! I'll close this issue, as this is working according to spec. 🙆

**Comment by cpboyd** [comment]
Thanks for the clarification!

I guess I need to brush up on the HTML5 documentation.

**Comment by notwaldorf** [comment]
No worries! :)
