### ISSUE TITLE
Document --paper-transition-easing mixin

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-input#334]
The `paper-input-container` has the `--paper-transition-easing` mixin:
- [L145](https://github.com/PolymerElements/paper-input/blob/master/paper-input-container.html#L145)
- [L155](https://github.com/PolymerElements/paper-input/blob/master/paper-input-container.html#L155)
- [L207](https://github.com/PolymerElements/paper-input/blob/master/paper-input-container.html#L207)

But there isn't documented.

**Comment by notwaldorf** [comment]
Huh, I always thought this was a mixin we were applying _from_somewhere, but that's totally not true. 👍 to documenting it!

**Comment by abdonrd** [comment]
@notwaldorf yeah, I always thought this was a mixin we were applying from `paper-styles`. But no. :sweat_smile:

**Comment by abdonrd** [comment]
As far as I know, the Polymer Elements are not going to continue developing. So I close this issue.
