### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by reinert** [PolymerElements/paper-input#340]
After some trial and error, researching and code reading I realized there's no well-defined support for resetting a paper-input element (and similar) to its initial state.

I'm using complex forms with auto-validation and resetting them is cumbersome because I have to adjust label style, error style, input value, etc. I cannot manipulate `invalid` property manually because it breaks `autoValidate` bahavior. Also, by setting the value of a input to null it doesn't reset the label position.

I suggest paper-input (and every other input element) should have a public `reset()` method, so we could easily and neatly reset the element to its very initial state.

**Comment by reinert** [comment]
Related issue: https://github.com/PolymerElements/iron-form/issues/27

**Comment by notwaldorf** [comment]
`reset` only makes sense in the context of a form, so it's the form who should keep track of the initial values of elements (for example, the native `<input>` does not have a `reset()` either). I have re-opened this on `iron-form`, and will fix it there.

**Comment by reinert** [comment]
It's true that the native input element does not have a reset method. But, should we be so inflexible as not to rethink certain standards and improve them? The web-components movement is pushing us towards a new way of thinking of web elements. 

In the context of the problem above, we can notice that old input elements didn't have complex behavior like validation, floating labels, and so on. These are enhancements by the paper-input (and similar) element. And each different input element may have different behaviors on how to treat such things. I believe we could approach the problem of resetting a whole form, with miscellaneous elements, by dividing the problem into other small problems. Solving each small problem in its own context would be a lot easier and much better to test and maintain. Divide and conquer is a classic proven approach in the computer science. The problem of resetting a form can clearly be modeled as the problem of resetting a collection of input elements which, and resetting a single input element can be modeled as the problem of resetting a collection of behaviors. 

Thinking in this 'simple' problem like that can scare us at first, maybe making it more complex than necessary. But, in fact, it's what this problem really is. Although it would take longer to solve it, the solution as a whole would be so much more stable and maintainable. Just think of a specific element or behavior changing some aspect of its current logic and reflecting in failing the test of the iron-form reset method. If, instead, the iron-form reset just calls each input reset we could be sure that it would never fail due to its own fault.

This is just my point of view about the problem. I don't expect you to accept my suggestion without a good reason. That's why I tried to make myself clearly as possible. The polymer project has a very receptive spirit and my intention is to contribute with it, be it by discovering bugs, discuss ideas to make it better, as also get hands dirty on solving the pending issues (which I've done lately). I hope I could help you guys someway here and not only disturb unnecessarily.
