### ISSUE TITLE
SSN demo inputs broken into multiple lines with recent update

### ISSUE THREAD

**Issue by kbenjamin** [PolymerElements/paper-input#353]
I know it's just a demo but it's a useful one I'm using in production. One of the recent releases seems to have broken the SSN demo.

Tested under Chrome & Edge.

Inputs act like display:block instead of display:inline but that doesn't seem to be the actual problem. Not sure what's changed or where.

**Comment by notwaldorf** [comment]
Fixed by https://github.com/PolymerElements/paper-input/pull/348
