### ISSUE TITLE
Inputs like the SSN example on the demo page don't have a horizontal layout anymore

### ISSUE THREAD

**Issue by miztroh** [PolymerElements/paper-input#357]
https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html&active=paper-input

![ssn](https://cloud.githubusercontent.com/assets/2515209/13674274/73d0f2d0-e6a2-11e5-9a38-a67edba6a46d.png)

**Comment by notwaldorf** [comment]
The demo has been fixed on master, but hasn't propagated to the catalog yet.
