### ISSUE TITLE
char-counter is off when using a text area

### ISSUE THREAD

**Issue by hereiam133** [PolymerElements/paper-input#358]
The char-counter is off when using a text area and adding a new line after in the text (ie, type something and hit enter).

A fix is add .replace(/\n/g, "\r\n") before grabbing the length so .replace(/\n/g, "\r\n").length

**Comment by notwaldorf** [comment]
What platform are you seeing this on? Here's a sample jsbin (http://jsbin.com/sekuhoz/edit?html,output), where each new line counts as `1` character on Chrome/Safari/FF.

We used to count it as `2`, but in practice this ended up looking weird: the users of the textarea don't know a new line is `\r\n` (and shouldn't need to) and assumed that when you pressed "Enter", this should only count towards 1 character. This is consistent to how, for example, the Twitter char counter works.

**Comment by notwaldorf** [comment]
Closing, as there hasn't been an answer in a while
