### ISSUE TITLE
Can't set the input value via the attribute

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/paper-input#36]
```
<paper-input label="label" value="Hello World"></paper-input>
```
produces:
![screen shot 2015-05-21 at 6 31 34 pm](https://cloud.githubusercontent.com/assets/116360/7762317/a33ffd60-ffe7-11e4-8fc3-83f1849bcd64.png)

**Comment by JaySunSyn** [comment]
Same problem here..

**Comment by JaySunSyn** [comment]
@frankiefu check your iron-input version. It has to be Version 0.9.0

**Comment by frankiefu** [comment]
I am using bower install to get the latest.
paper-input#0.9.4 bower_components/paper-input
├── iron-autogrow-textarea#0.9.4
├── iron-input#0.9.5
├── paper-styles#0.9.5
└── polymer#0.9.0

So looks like a regression in 0.9.5

**Comment by m4b** [comment]
I noticed a similar regression.

However, regular binding with input seems to work, e.g.:

````js
  <dom-module id="input-broken">
    <style>
    </style>
    <template>


      <paper-input id="testInput" bind-value="{{test}}" value="{{test}}" label="Sweet Label"></paper-input>
      <input value="{{test::input}}" />

      <paper-button on-tap="setTest1">Button 1</paper-button>
      <paper-button on-tap="setTest2">Button 2</paper-button>

    </template>
  </dom-module>

  <script>
    Polymer({
      is: "input-broken",

      properties: {
        test: {
          type: String,
          value: "",
          notify: true
        }
      },

      setTest1: function() {
        console.log("setting test 1: ");
        this.test = "Test";
      },

      setTest2: function() {
        console.log("setting test 2: ");
        this.test = "Another";
      }

    });
  </script>
````

The regular input field with data-binding will get set, but the `<paper-input>` won't show the new `test` data-bound value --- if however you `$0.value` the `<paper-input>` it returns the correct value, it just doesn't seem to be displaying.

**Comment by JaySunSyn** [comment]
Ok, I've found it. The reason lies in IronFormElementBehavior (value property) (I guess) not in iron-input but iron-input 0.9.5 includes it as a behavior. I deleted the line "Polymer.IronFormElementBehavior" from iron-input.html and it works again.. Not nice but it works for now..

**Comment by notwaldorf** [comment]
Gah, `Polymer.IronFormElementBehavior` is my bad. Looking.

**Comment by m4b** [comment]
@JaySunSyn confirmed this fixes the issue for me as well.

Although not sure why ;)

It preserves the `value` in the above code, even when user types, and when inspecting via `$0.value`

**Comment by notwaldorf** [comment]
@m4b I believe the `value` property from the behaviour is stomping over the `iron-input`'s native `value` property, and then `iron-input` is hosed, which means `paper-input` isn't notified of any text changes etc. etc. :(

**Comment by JaySunSyn** [comment]
Thanks @notwaldorf :)

**Comment by charleskoehl** [comment]
I found a way to fix this:

Just add the following property to the element:

      value: {
        type: String,
        reflectToAttribute: true
      }
