### ISSUE TITLE
Demo bug

### ISSUE THREAD

**Issue by khoanguyenlio** [PolymerElements/paper-input#362]
In demo on paper-input, I found this: 
![bugdemo](https://cloud.githubusercontent.com/assets/9152575/13840553/aee114dc-ec55-11e5-86ec-91e545980825.jpg)
It's problem of  type="number" or paper-input?

**Comment by notwaldorf** [comment]
There seems to be a problem with `input type="number"` and invalid values.

**Comment by notwaldorf** [comment]
Closing as duplicate of https://github.com/PolymerElements/paper-input/issues/362 (since that one has a better title)
