### ISSUE TITLE
Minimum version of paper-styles in bower.json should be 1.1.4

### ISSUE THREAD

**Issue by var-const** [PolymerElements/paper-input#366]
Starting from [this commit](https://github.com/PolymerElements/paper-input/commit/488fcf10a0ace75666066f3c0e621017c36d91fe), paper-input element uses --error-color, which is only available in paper-styles starting from version 1.1.4. The required version of paper-styles in bower.json should be bumped accordingly.

**Comment by notwaldorf** [comment]
Sure, that sounds right. Would you like to send a PR to fix that?
