### ISSUE TITLE
Input label is not removed when content is typed in.

### ISSUE THREAD

**Issue by brks** [PolymerElements/paper-input#37]
As shown below:

![Proof 1](https://cloud.githubusercontent.com/assets/5854502/7777558/09a15700-00bc-11e5-84bc-735df16695e1.png)
![Proof 2](https://cloud.githubusercontent.com/assets/5854502/7777559/09a4564e-00bc-11e5-9886-e70580e49d2c.png)
![Proof 3](https://cloud.githubusercontent.com/assets/5854502/7777560/09a47b88-00bc-11e5-88f6-2f2d43ed06f2.png)

**Comment by brks** [comment]
On further investigation, removing the line ``` Polymer.IronFormElementBehavior ``` from iron-input.html solves the problem, similarly to this issue https://github.com/PolymerElements/paper-input/issues/36

**Comment by notwaldorf** [comment]
Closing as duplicate. Sorry!
