### ISSUE TITLE
Missing `title` property

### ISSUE THREAD

**Issue by MeTaNoV** [PolymerElements/paper-input#370]
### Description
`paper-input` is mapping a property `title` which is not declared in neither `PaperInputBehavior` nor `IronFormElementBehavior`.

### Solution
Add `title` in the property list of `PaperInputBehavior` so that it will be documented properly.

PS: I can PR this if requested!

**Comment by notwaldorf** [comment]
Title (like tabindex) is a native HTMLElement attribute and doesn't need to be redefined as a Polymer property.
