### ISSUE TITLE
paper-input not loading in IE 11

### ISSUE THREAD

**Issue by PaulHMason** [PolymerElements/paper-input#373]
### Description
paper-input not loading in IE 11 (throwing exception)

### Expected outcome
Should render as expected.

### Actual outcome
The paper-input doesn't render, and the following exception is thrown:

Unable to get property 'replaceChild' of undefined or null reference.

The exception is thrown in line 1037 of webcomponents-lite.js (t.parentNode.replaceChild(s.cloneNode(true), t);)  

Where t is HTMLUnknownElement (parentNode is null).

I can't see exactly what the problem is, but it appears to have something to do with paper-input-container and/or templates (the following is buried in the exception: "style-scope paper-input-container").

### Live Demo
I can't get a jsbin to show this.

### Steps to reproduce
The following illustrates the issue:

````
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">
    <title>input error</title>
    <script src="../../webcomponentsjs/webcomponents-lite.js"></script>
    <link rel="import" href="../../paper-input/paper-input.html" />
</head>
<body unresolved>
    <template is="dom-bind" id="app">
        <paper-input></paper-input>
    </template>
</body>
</html>
````

### Browsers Affected

It works fine in Chrome and Firefox, but not in IE11.

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [x] IE 11
- [ ] IE 10

**Comment by PaulHMason** [comment]
The issue is definitely related to `paper-input-container` - if you replace `paper-input` with `paper-input-container` you get the same error.

**Comment by PaulHMason** [comment]
And further - it's just a template issue. Just this doesn't work in IE11 anymore.

````
<template is="dom-if" if="[[canShow]]">
    <div>Template</div>
</template>
````

I'll move over to the webcomponents.js repo, but I'll leave this here in case someone else runs into the issue.

**Comment by notwaldorf** [comment]
Closing this, since it's not a `paper-input` issue. @PaulHMason If you could link the webcomponent.js issue in here, that would be great!

/cc @kevinpschaaf
