### ISSUE TITLE
interop with webshim's form polyfill no longer works in Safari

### ISSUE THREAD

**Issue by jab** [PolymerElements/paper-input#375]
### Description
Safari [still doesn't fully implement html5 form validation](http://caniuse.com/#feat=form-validation) :cry:. [webshim](https://github.com/afarkas/webshim) is one of the recommended polyfills to enable "invalid input" error bubbles in Safari. `paper-input` used to work with webshim's form polyfill in Safari (as of at most a couple months ago), but no longer does.

### Expected outcome

Trying to submit an invalid form in webshim-polyfilled Safari shows an error bubble under the invalid paper-input.

### Actual outcome

No error bubble is shown.

### Live Demo

- native input works: https://jsfiddle.net/jab_/vmqxff1v/
- paper-input doesn't work: http://jsfiddle.net/jab_/2vcdcgsu/

### Steps to reproduce

1. Load the above demos in Safari
2. Click the submit button without filling in the required input (i.e. leaving it invalid)
3. Observe no error bubble is shown for paper-input

### Browsers Affected

- [x] Safari 9.1
- [ ] IE 11
- [ ] IE 10

Any idea if something small was changed that broke this / is there interest in making this work again? Happy to test other browsers and try to contribute to a fix if so.

**Comment by jab** [comment]
Just noticed that if you submit the form by pressing enter while the paper-input has focus rather than by clicking the submit button, the webshim-polyfilled error bubble does show in Safari! Could this be a clue?

**Comment by notwaldorf** [comment]
I don't really know how the webshim works, but it seems that it adds a `user-error` or `user-success` class to the nested `iron-input`, which I guess triggers some magic and pops up that bubble. That class seems to be applied correctly (after the first click), but doesn't actually pop up the bubble. I've also noticed that if I click like 10 times in a row, it brings up the bubble.

**Comment by notwaldorf** [comment]
I'm also seeing an error in the console related to the webcomponents polyfill:

<img width="608" alt="screen shot 2016-04-06 at 10 11 39 pm" src="https://cloud.githubusercontent.com/assets/1369170/14341217/9699d9be-fc44-11e5-88e7-bd3928e98918.png">


/cc'ing @azakus as a hail mary pass

**Comment by jab** [comment]
Thanks so much for taking a look at this @notwaldorf!

Regarding the "Refused to get unsafe header" error, that looks like an artifact of the way dependencies are loaded in the jsfiddle environment (CORS stuff). This reproduces in a same-origin environment too, so I think that error is a red herring. I whipped together https://github.com/jab/paper-input-issue-375 to demonstrate this.

I tried the new test in IE 11 and IE 10, and the polyfill still works fine there (updated the description above). I wonder if it's worth testing this in Safari 9.0. I'm pretty sure this used to work in Safari, but I upgraded to 9.1 when it came out recently, and unfortunately don't have a 9.0 env I can test in. (On the other hand, if there's some recent change in Polymer that more likely accounts for this, maybe not worth testing Safari 9.0.)

One other thing I noticed is that if you fill in the first input in the new test, but leave the second one invalid, then click submit, sometimes a polyfilled error bubble is shown under the first input, even though it's valid, but with the error message for the second input.

If Polymer recommends some alternative polyfill library, or some other best practice for working around Safari's incomplete html5 form implementation, I'd be happy to give that a shot instead of webshim. Just sad it's 2016 and this is still an issue! :cry:

**Comment by notwaldorf** [comment]
It sounds like this is a Safari problem, if it works in literally every other browser that's not Safari (also, again, the webshim is putting the right CSS class on the input, just not showing the bubble).

**Comment by jab** [comment]
I tried to find a Safari 9.0 env I could test with, but https://saucelabs.com/beta/manual is currently giving "Manual sessions are temporarily disabled." :cry:

Totally out of the question for paper-input to provide its own error bubbles for browsers that don't support this natively, right? :innocent:

**Comment by notwaldorf** [comment]
`paper-input` will turn red, and you can use the `error-message` property to display an error message, but it's unlikely we would implement these kind of bubbles, since they would clash with the native UI, and they go against the Material Design spec

**Comment by jab** [comment]
FWIW, I was able to use Sauce Labs to test on an older version of Safari, and it happened there too (video attached). So with that, I've reproduced in all of these environments:
iOS 9.1 Safari 9.0 (13B17)
iOS 9.3.1 Safari 9.0 (13E238)
OS X 10.11.4 Safari 9.1 (601.5.17)
Maybe it was never working in Safari after all, and I only thought it was because I was submitting via keyboard rather than click.

Regarding using `error-message` instead, is `error-message` designed to allow you to show a different error message depending on in what way the input is invalid? e.g. Can it say "please fill out this field" when a required field is missing, and "letters only!" if the user enters a non-letter? That's something that native html5 error bubbles can do, but I don't see any reference to that capability in the https://elements.polymer-project.org/elements/paper-input docs or demos.

Regarding the clashing, do you happen to know if the Chrome team is working on making more of Chrome's native UI comply with the Material Design spec? It sounds like to be compliant with the spec, we'd actually have to shim Chrome to not display its native error bubbles. It feels funny when we have to go so far out of our way to get a compliant UI in our own browser. Maybe you're no stranger to the feeling? :)

![paper-input-issue-375](https://cloud.githubusercontent.com/assets/64992/14392939/1b0596cc-fd92-11e5-9cd8-886cf81190cb.gif)

**Comment by jab** [comment]
Come to think of it, if you go to the [iron-form demo](https://elements.polymer-project.org/elements/iron-form?view=demo:demo/index.html) in e.g. Chrome and click submit without filling out the form, Polymer isn't doing anything to stop Chrome from displaying its native error bubbles.

![screen shot 2016-04-08 at 15 22 56](https://cloud.githubusercontent.com/assets/64992/14395118/d1016450-fd9d-11e5-812e-5f09f3e509c9.png)

In light of the discussion above, when you submit an invalid form, should Polymer suppress any native error bubbles and instead render those error messages in `paper-input-error` elements? For error bubble-capable browsers, this would bring the UI in line with the Material Design spec, and for incapable browsers, it would provide a consistent validation UI.

**Comment by notwaldorf** [comment]
If you want to supress the native bubbles, there's already the `disable-native-validation-ui` attribute on `iron-form`

I don't know what the priority of the Chrome's team is to update the UI bubbles to Material Design -- they're already very inconsistent across browsers, so I would expect it to be fairly low. I will go and ask around, though

**Comment by notwaldorf** [comment]
I'm going to close this issue, since I don't see what we can do to make the polyshim work. It's not exactly in `paper-input`'s goal to work with every third party library out there, and there's no evidence this ever worked (also, debugging shows that the right styles are applied to the element, the shim just doesn't use them correctly).

Regarding `error-message`, I would recommend you update the message yourself, using the `Validity` API. See [this thread](https://github.com/PolymerElements/paper-input/issues/292#issuecomment-169169711) for a similar discussion, and this [jsbin](http://jsbin.com/zizeri/edit?html,output) for a demo.

**Comment by jab** [comment]
Thanks for those references and for the time you spent looking into this @notwaldorf, much appreciated.

**Comment by notwaldorf** [comment]
No worries! Sorry that the resolution wasn't better.

**Comment by jab** [comment]
Aw, not up to Polymer to fix everything :)
