### ISSUE TITLE
Double focus and double blur

### ISSUE THREAD

**Issue by ellenaua** [PolymerElements/paper-input#382]
We have multiple paper-inputs on page, and each of them has on-focus and on-blur handler assigned. If I navigate inputs using mouse clicks - everything is OK, on-focus event happens once I click some input, and on-blur happens when I leave it.
```
"input1 focused"
"input1 blurred"
"input2 focused"
"input2 blurred"
"input3 focused"
"input3 blurred"
```

But if I havigate using Tab key, then during "focus" input emits these three(!) events:
```
"input3 focused"
"input3 blurred"
"input3 focused"
```
and when I leave that input, it emits "blur" as expected:
`"input3 blurred"`

It seems to be non-important bug.. but: we need to focus input1 when blur happens on input3. But blur on input3 happends too early: when I'm just going to focus it. I think "blur" event should not be emitted when user navigates to an input. Bug happens only if I navigate using Tab key. Browser: Chromium Version 48.0.2564.82 Ubuntu 14.04 (64-bit)

Here's the jsbin https://jsbin.com/vecagi/edit?html,console,output

**Comment by notwaldorf** [comment]
Argh, yeah, I think this is happening because when you tab to the `paper-input`, we have to focus the inner `<input>`, which will also cause a `blur` on the parent `paper-input`. I don't think this can be avoided at the moment. :(
