### ISSUE TITLE
paper-input makes IE11 horizontal scrollable

### ISSUE THREAD

**Issue by JMuratha** [PolymerElements/paper-input#383]
### Description
<paper-input> makes IE11 horizontal scrollable when text is entered

### Expected outcome
page stays as it is 

### Actual outcome
page gets scrollable

### Steps to reproduce
[issue.zip](https://github.com/PolymerElements/paper-input/files/236561/issue.zip)

1. unzip issue.zip
2. cd into unzipped directory und call "node server.js"
3. open IE11 and navigate to localhost:8080
4. enter text into the paper-input

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [x] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
Hah, I'm not going to download a zip from the internet and run node on it :)

Please provide a JSBin with reproducible steps as explained in the [CONTRIBUTING.md](https://github.com/PolymerElements/paper-input/blob/master/CONTRIBUTING.md), or a link to a deployed site, and we can re-open this issue then.
