### ISSUE TITLE
Text area label doesn't float when a placeholder is provided

### ISSUE THREAD

**Issue by briem-bixly** [PolymerElements/paper-input#385]
In the js fiddle provided in issue #53 http://jsbin.com/cuqulajuto/3/edit, if you add a placeholder to the input in the top example, the placeholder and label overlap. See my edits to the js fiddle: http://jsbin.com/robiselifa/edit?html,output.

**Comment by notwaldorf** [comment]
You should set `always-float-label` manually in this case. See https://github.com/PolymerElements/paper-input/issues/163 for a discussion about this.
