### ISSUE TITLE
Focused property is not cleared when using shift+tab

### ISSUE THREAD

**Issue by tehapo** [PolymerElements/paper-input#386]
### Description
The `focused` property (and corresponding attribute) is not cleared if focus is lost via navigating the page with `shift+tab` keys. When going past a `paper-input` with `tab` key, the `focused` property is correctly cleared.

### Expected outcome

The `paper-input` should not have `focused` as `true` when focus was already lost.

### Actual outcome

The `paper-input` has `focused` as `true` and the `focused` attribute present.

### Live Demo
See the animated gif with a background style bound to the `focused` attribute.
![paper-input-focused](https://cloud.githubusercontent.com/assets/368220/15014111/aece3cfe-120c-11e6-957e-b5a9912a180d.gif)

### Steps to reproduce
1. Put couple of `paper-input` elements in the page.
2. Open the page in a web browser.
3. Navigate the page with `tab` and `shift+tab` and see how `focused` attribute behaves.

### Browsers Affected
At least the following:
- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
@tehapo I think that fix should be somewhere in https://github.com/PolymerElements/paper-input/blob/master/paper-input-behavior.html#L448. Are you interested in sending a PR to fix this? It would be much appreciated!

**Comment by tehapo** [comment]
@notwaldorf Sure, I'll see if I can come up with a PR later this week.

**Comment by notwaldorf** [comment]
Thanks so much! 🍰
