### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by jerryf196** [PolymerElements/paper-input#39]
Any small example how to style a paper-input? I need to change the color of the line under the input field.

**Comment by morethanreal** [comment]
Docs added.

**Comment by Frikki** [comment]
@morethanreal Where?

**Comment by notwaldorf** [comment]
@Frikki in the last commit, @morethanreal added more mixins: https://github.com/PolymerElements/paper-input/commit/880be8ae50cec521dba0c7d6d4c5a30cebc7a14a#diff-a9a2db156d9736c00b0125ad8fa7de30R70. They should show up in the catalog at the next catalog release.
