### ISSUE TITLE
Paper-textarea label is offset from underline

### ISSUE THREAD

**Issue by kreinholt** [PolymerElements/paper-input#394]
### Description
Paper-textarea label is offset 4 pixels above the underline whereas paper-input is not offset at all. If they are meant to appear differently, there probably needs to be a more substantial difference.

### Expected outcome
Both paper-input and paper-textarea appear similar before any text is entered

### Actual outcome
Paper-input and paper-textarea appear differently.

### Live Demo
https://jsbin.com/dayedifeqo/edit?html,output

### Steps to reproduce
Add paper-input, give label.
Add paper-textarea, give label.

**Comment by notwaldorf** [comment]
@kreinholt I don't think that's intended. Would you be interested in submitting a PR to fix this?
