### ISSUE TITLE
invalid validation pattern

### ISSUE THREAD

**Issue by jodekirk** [PolymerElements/paper-input#395]
Up until late May this input pattern worked fine. Something updated after I did a `bower update` and now it's considered an invalid regular expression.

Can test and see it fails by updating paper-input-error.html to this:
```<input is="iron-input" id="i" pattern="[\ A-Za-z0-9~!#()_+=\-\[\]\:;',\.]+">```

Is there a different way to write this regular expression to allow spaces and numbers and letters and a few special characters? Or is the validate command incorrect?

After updating paper-input-error.html the web component test fails with this in the console:
```
paper-input-error.html
console.js:65basic
console.js:65error message only appears when input is invalid
VM3054 iron-input.html:279
Pattern attribute value [\ A-Za-z0-9~!#()_+=\-\[\]\:;',\.]+ is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /[\ A-Za-z0-9~!#()_+=\-\[\]\:;',\.]+/: Invalid escapevalidate @ VM3054 iron-input.html:279
_handleValueAndAutoValidate @ VM3060 paper-input-container.html:536
_onValueChanged @ VM3060 paper-input-container.html:512
fire @ VM3049 polymer.html:1277
_bindValueChanged @ VM3054 iron-input.html:178
_observerEffect @ VM3049 polymer.html:1562
_effectEffects @ VM3049 polymer.html:1405
_propertySetter @ VM3049 polymer.html:1389
setter @ VM3049 polymer.html:1468
(anonymous function) @ paper-input-error.html?dom=shadow:56callFn @ mocha.js:4471
Runnable.run @ mocha.js:4464
Runner.runTest @ mocha.js:4934
(anonymous function) @ mocha.js:5040
next @ mocha.js:4854
(anonymous function) @ mocha.js:4864
next @ mocha.js:4796
(anonymous function) @ mocha.js:4832
timeslice @ mocha.js:75
console.js:57
error is not visibility:hidden: expected 'hidden' to not equal 'hidden'
  Context.<anonymous> at paper-input-error.html:57
```

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
I don't think I can reproduce this issue. Here's a jsbin with the pattern you provided: http://jsbin.com/wazoje/edit?html,output

If i type `asdfasdf|||` and press the `validate` button, the input becomes red and invalid. If you can still repro this, please post a jsbin so that I can look at the code you're using...

**Comment by jodekirk** [comment]
I get the error using Chrome dev 53 with your jsbin example by typing "abc " in the input.
![image](https://cloud.githubusercontent.com/assets/1869259/16266889/b69248ac-384c-11e6-8e52-c241ef92e1b3.png)

**Comment by jodekirk** [comment]
My original pattern doesn't work in Chrome dev 53:
```pattern="[\ A-Za-z0-9~!#()_+=\-\[\]\:;',\.]+"```
But this pattern does work:
```pattern="[ A-Za-z0-9~!#()_+=\-\[\];',\.]+"```
I'm guessing the special character escape "\" is not required before a space or colon so that's what caused Chrome to call it an invalid pattern. It works now with the new pattern.
