### ISSUE TITLE
<paper-textarea> doesn't remove line breaks when setting the input elements value="";

### ISSUE THREAD

**Issue by RonMen** [PolymerElements/paper-input#396]
### Description
Using ```<paper-textarea></paper-textarea>``` as a input-element to use SHIFT+ENTER to add line breaks within the input-text it seems to not completely setting the paper-textarea's value property, it doesn't remove all line breaks from the last input, so the scrollbar will be shown and the next input begins after a line break (or more).

### Expected outcome
Changing the paper-textarea's value property to ```this.$.textInput.value = "";``` should really set the value property to an empty string and therefore remove the line breaks from the old input.

### Actual outcome
It seems on changing the paper-textarea's value property to ```this.$.textInput.value = "";``` doesn't remove all line breaks.

### Steps to reproduce
1. put a <paper-textarea></paper-textarea> element in the page
2. define a handler to change the input.value maybe on ENTER key (not SHIFT+Enter since this should produce the line breaks)
3. type something, text with line breaks (SHIFT+ENTER)
4. click ENTER to fire up the handler
5. type again, you should have line breaks within the element

### Browsers Affected/Tested for now
- [x] Chrome
- [x] Firefox

**Comment by notwaldorf** [comment]
Would you mind providing a JSBin with reproducible steps, so that we can take a look at the code, please?
