### ISSUE TITLE
A11y: Upon showing an error using error-message attribute no verbalisation is given

### ISSUE THREAD

**Issue by giltza** [PolymerElements/paper-input#408]
### Description
Error messages that are shown in response to invalid = true && error-message="<text here>" are not verbalized when using accessibility tools.

### Live Demo
https://jsfiddle.net/a3msv0tu/

### Steps to reproduce

1. Turn on a verbalisation acceability tool (ChromeVox/Voice Over/etc.)
2. Update using code the paper-input to invalid="true" and error-message="This is an error message"

### Expected
Accessibility tool should 'speak' the error message that appears.

### Actual result
The error message is not 'Spoken' 

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
Fixed in https://github.com/PolymerElements/paper-input/pull/409
