### ISSUE TITLE
paper-input on IE10 is sadness 

### ISSUE THREAD

**Issue by notwaldorf** [PolymerElements/paper-input#41]
😭
![pasted_image_at_2015_05_26_02_55_pm_720](https://cloud.githubusercontent.com/assets/1369170/7824429/ac6bb162-03b7-11e5-9d6c-01e55c13df89.png)

**Comment by notwaldorf** [comment]
Oh this might not be the input. It throws this (sorry for the screenshots, I can't copy paste)
![screen shot 2015-05-26 at 3 23 46 pm](https://cloud.githubusercontent.com/assets/1369170/7825080/c7c85180-03bd-11e5-8329-1ca5479ade33.png)

**Comment by morethanreal** [comment]
Appears to be working.

**Comment by notwaldorf** [comment]
Yeah, it was a webcomponents bug in the end.
