### ISSUE TITLE
paper-input does not set the `for` attribute on the label tag

### ISSUE THREAD

**Issue by yrral86** [PolymerElements/paper-input#410]
The `for` attribute is used to link the label to the input.  This is very useful when writing tests using capybara because when they are properly linked, you can select the input to fill in by using the label text.  Since paper-input does not set the `for` attribute, the default behavior does not work and we have to set an id on the paper-input and then use a custom paper_fill_in function every time we want to fill in a paper-input.

**Comment by notwaldorf** [comment]
Fixed in https://github.com/PolymerElements/paper-input/pull/411
