### ISSUE TITLE
Weird behavior when bind with array using dom-repeat

### ISSUE THREAD

**Issue by Holi0317** [PolymerElements/paper-input#413]
Perhaps this is a issue with dom-repeat. But I am not that sure which end is causing this issue.

### Description
This happens when I try to bind array to paper-input.

[![](https://img.youtube.com/vi/F55Re09GcOc/0.jpg)](https://www.youtube.com/watch?v=F55Re09GcOc)

(Console logs the array value when paper-input fires changes event)

The array binded have correct data. But value in paper-input and rendered value is not.

Also, forcing the dom-repeat element to re-render causes weird data populated into paper-input.

### Expected outcome
Value in paper-input should have same value with array binded with dom-repeat

### Actual outcome
Weird and incorrect data rendered and paper-input value are not correct.

### Live Demo
https://jsbin.com/dugaxivapu/edit?html,output

### Steps to reproduce
1. Create an array property and bind that into dom-repeat
2. Inside dom-repeat template, place a paper-input element
3. Run the page. Change paper-input value in the last element. The first one syncs value with the last one.

### Browsers Affected
Tested on Chromium 52.0.2743.82

**Comment by Holi0317** [comment]
Tested with native input element but the bug still exists. Therefore it is a bug with polymer itself. Closing this.

**Comment by cormacguerin** [comment]
For Posterity it seems you can work around this by adding $
ie value$="{{item}}"
