### ISSUE TITLE
Unwanted outline border when focused 

### ISSUE THREAD

**Issue by dschuyler** [PolymerElements/paper-input#415]
Create a paper-input or a paper-dropdown-menu (which internally uses a paper-input).
Click at the top edge of the paper-input.

### Description
An unwanted outline border will appear (on Chrome, it's defined in the default html.css file).

The paper-input already has a good focused indicator (the blue underbar). The outline is redundant and unwanted.

Bad:
![image](https://cloud.githubusercontent.com/assets/13840539/17262663/8ca3205e-5591-11e6-8c4c-fd5fa5365864.png)

Good:
![image](https://cloud.githubusercontent.com/assets/13840539/17262549/eeb42730-5590-11e6-86c1-75e11bfbd84a.png)

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
This is only reproducible in the shadow dom, right?

**Comment by dschuyler** [comment]
That may be true. I haven't done testing without being in shadow dom.
