### ISSUE TITLE
Using iron-autogrow-textarea inside a paper-input-container

### ISSUE THREAD

**Issue by josericaurte** [PolymerElements/paper-input#422]
### Description
`paper-input-container` throws multiple errors when using with an `iron-autogrow-textarea` element.

### Expected outcome
No errors.

### Actual outcome
Multiple errors are thrown.

The first error occurs during the `attached` lifecycle callback.
```
Uncaught TypeError: Cannot read property 'addEventListener' of null
```

The second error occurs during the `_onBlur` method.
```
Uncaught TypeError: Cannot read property 'bindValue' of null
```

### Live Demo
https://jsbin.com/dimifocofe/edit?html,console,output

### Steps to reproduce
Error 1
1. Put a `paper-input-container` element in the page.
2. Put a `iron-autogrow-textarea` element inside the `paper-input-container`
***
Error 2
1. Click the `paper-input-container`.
2. Click outside the `paper-input-container`

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [ ] Safari 8 *(not tested)*
- [ ] Safari 7 *(not tested)*
- [x] Edge
- [x] IE 11
- [ ] IE 10 *(not tested)*

**Comment by notwaldorf** [comment]
If you look at the [docs](https://github.com/PolymerElements/paper-input/blob/master/paper-input-container.html#L39), you need to specify `class="paper-input-input"` on the custom element, so that the container knows how to update the input. Updated jsbin: https://jsbin.com/tacolij/edit?html,console,output with that class.

You can also look at the `paper-textarea` [implementation](https://github.com/PolymerElements/paper-input/blob/master/paper-textarea.html#L52), that is also a wrapper around `iron-autogrow-textarea`

Hope this helps!

**Comment by josericaurte** [comment]
Thanks! I took *custom input element* to mean something that I make myself and not what's bundled with paper-input, such as `iron-autogrow-textarea`.

My expectation was that it would work out of the box. The description kinda alludes to that as well:
```
`<paper-input-container>` is a container for a `<label>`, an `<input is="iron-input">` or
`<iron-autogrow-textarea>` and optional add-on elements such as an error message or character
counter, used to implement Material Design text fields.
```

Also, the `_inputSelector` property is looking for `input`, `textarea`, and `.paper-input-input`
```javascript
_inputSelector: {
        type: String,
        value: 'input,textarea,.paper-input-input'
      }
```

Using a `textarea` inside a `paper-input-container` doesn't make much sense as you're gonna get a scrollbar. Amirite?

**Comment by notwaldorf** [comment]
You might want a non-growing textarea with a scrollbar, that just looks material design-y: https://jsbin.com/vobura/edit?html,console,output. I don't know why would would, but if you do, you can :)

Would you like to send a PR to update that line to say "an `<input is="iron-input">` or `<textarea>` instead?

**Comment by josericaurte** [comment]
Sure, should I create a new issue?

Btw, love your talks. 👍

**Comment by notwaldorf** [comment]
Nah, you can keep this issue, and reference it in the PR. All good.

Thanks! That's awesome to hear! 😍
