### ISSUE TITLE
paper-input type="number" accepts the letter "e"

### ISSUE THREAD

**Issue by donpir** [PolymerElements/paper-input#426]
### Description

the paper-item with type="number" accepts the letter "e". In addition, when typed as first letter "e" the label does not float on top.

### Live Demo

https://jsbin.com/zicekofafo/edit?html,output

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
This is working as intended. The native `<input type="number">` also accepts this value -- it's because `e` denotes exponent, so `10e7` is a valid number.
