### ISSUE TITLE
The value of paper-textarea isn't aligned in Shadow DOM

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-input#441]
### Description

The value of paper-textarea isn't aligned in Shadow DOM.
### Expected outcome

![screen shot 2016-09-16 at 13 01 48](https://cloud.githubusercontent.com/assets/1007051/18583899/c5429668-7c0d-11e6-9da3-b3b13e353e4b.png)
### Actual outcome

![screen shot 2016-09-16 at 13 01 18](https://cloud.githubusercontent.com/assets/1007051/18583901/c883ddbe-7c0d-11e6-8886-17bdb10a41b1.png)
### Live Demo

https://jsbin.com/xuyusodote/edit?html,output
### Browsers Affected

- [x] Chrome

**Comment by vinerz** [comment]
+1, it is due to 2px padding of native user agent css.

**Comment by abdonrd** [comment]
As far as I know, the Polymer Elements are not going to continue developing. So I close this issue.
