### ISSUE TITLE
Basic and [focused] mixing for paper-input

### ISSUE THREAD

**Issue by Westbrook** [PolymerElements/paper-input#463]
### Description
I would like to be able to use `custom-styles` to set styling across all of the `paper-input` elements in my app. There are a number of really useful ones internal to `paper-input-container` but nothing at the top level.

### Expected outcome
Basic and [focused] styles can be applied at the app level to `paper-input` elements across an application.

### Actual outcome
Included elements are needed locally to each custom element that employs the input to access `paper-input` and `paper-input[focused]`.

### Steps to reproduce
1. Attempt to share custom styles to `paper-input` across an application.
2. Fail.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by robrez** [comment]
I was just coming here to request that focus styling be added to input-container.. we have `--paper-input-container-input`, but changing properties when the input is focused would be nice... eg: `--paper-input-container-input-focus`

I have a polymer webapp that is deployed for multiple customers, we allow full-theming per customer...  some have requested more "traditional" looking inputs...

![focus](https://cloud.githubusercontent.com/assets/1993389/20851137/26f486e6-b8a4-11e6-9f59-db16a1917a2a.png)

**Comment by notwaldorf** [comment]
Regarding the original request: I think that's more complicated than it sounds, because each individual element inside the `paper-input` is styled separately when the element is focused, so the mixin wouldn't really affect that.

There's already `--paper-input-container-focus-color` to change the colour, and mixins for `--paper-input-container-underline-focus` and `--paper-input-container-label-focus`. Is the only thing you're missing then, is `--paper-input-container-input-focus`?

**Comment by Westbrook** [comment]
It's possible that `--paper-input-container-input-focus` would achieve a similar goal as to what I'm looking to do. More specifically, I have the following file: 
```
<dom-module id="comps-input-styles">
  <template>
    <style>
	paper-input {
		display: block;
		box-sizing: border-box;
		border: solid 1px gray;

		--paper-input-container: {
			border: none;
			padding: 15px 20px;
		};

		--paper-font-subhead: {
			font-size: 100%;
		};

		--paper-input-container-color: rgb(64, 64, 64);
		--paper-input-container-focus-color: rgb(64, 64, 64);

		--paper-input-container-underline-focus: {
			display: none;
		};

		--paper-input-container-underline: {
			display: none;
		};

		--paper-font-caption: {
			display: none;
		};

		--paper-input-error: {
			display: block;
			color: red;
			top: 1.5em;
			right: -20px !important;
			left: -20px !important;
			font-size: 16px;
		};

		--paper-input-container-label: {
			position: static;
			display: inline-block;
			overflow: visible;
			font-size: 100%;
		};

		--paper-input-container-label-floating: {
			-webkit-transform: none;
			transform: none;
			width: var(--comps-input-label-width, 100px);
		};

		--paper-transition-easing: {
			-webkit-transform: none;
			transform: none;
			-webkit-transition: 0 0;
			transition: 0 0;

			-webkit-transform-origin: 50% 50% 0;
			transform-origin: 50% 50% 0;
			width: var(--comps-input-label-width, 100px);
		}

		--paper-input-container-input: {
			width: calc(100% - var(--comps-input-label-width, 100px));
			line-height: inherit;
		};

		--paper-input-container-invalid-color: red;

		@apply(--comps-input);
	}

	paper-input[focused] {
		border: solid 1px blue;
	}
    </style>
  </template>
</dom-module>
```

And, at current I have to apply this as a `<style include="comps-input-style"/>` and I was looking to apply it as `<style is="custom-style">` such that I didn't have to make it a hard dependency that always overwrote the paper styles in the components that I'm building to apply it.

I'll look into whether I can get those two top level styles applied with just the addition of `--paper-input-container-input-focus` or not and come back with an edit to the PR if that also addresses my issue.

**Comment by Westbrook** [comment]
It's possible that what I really want is a version of this component that has all of the sweet CSS Custom Properties, but none of the Paper Styles set to them...which is a very different ask.

I'm running into issues of Custom Property cascade that I didn't see before in trying to apply some of my overrides to the `--paper` styles. Wonder how I thought I had this working before?

**Comment by robrez** [comment]
Could you style the input as a whole based on `[focused]` in your composiing parent...

```
paper-input[focused] {
  border: solid 1px #eee;
}
```
https://jsbin.com/lidusinuni/edit?html,output

I really think the only thing missing that would be needed to support completely customizable paper-inputs is `--paper-input-container-input-focus`. Granted, using paper-input-container with a light-dom input child would allow you to style the input on focus, I think; still, I'd like to be able to do so when using paper-input directly.

**Comment by Westbrook** [comment]
@notwaldorf and @robrez you're right that it's `--paper-input-container-input-focus` that I'm really looking for, and I extended that with `--paper-input-container-input-invalid` to have similar access in that context as part of my updated PR. Hoisted the new mixins into the documentation as well. Hopefully #464 looks good to go now.

As an aside, @robrez have you had luck actually customizing `--divider-color` in `border: 1px solid var(--divider-color, #b6b6b6);`? Something on the order of https://jsbin.com/witeyunaye/1/edit?html,output

**Comment by notwaldorf** [comment]
Fixed in #464

**Comment by dman777** [comment]
Thanks...ran into this issue also :+1:

**Comment by robertop87** [comment]
in the older documentation I saw the --paper-input-container-input-disabled, currently there is no something similar. My goal is customize the style of the input, when the component is disabled without affect the other element like the label.
Example change the background-color for the input.
