### ISSUE TITLE
Not ideal validation behavior

### ISSUE THREAD

**Issue by honzabenes** [PolymerElements/paper-input#466]
Hello, I would like to suggest an improvement regarding the validation. The issue is that when the paper-input is set to auto-validate and the user starts typing the whole input validates(and gets red) even though the user didn't finish typing. I think that when the user is typing the input shouldn't be screaming that he's doing it wrong. I think the ideal approach is that of html5 input element. The referential [polymer shop app](https://shop.polymer-project.org/checkout) is the perfect example of the approach which in my opinion is the best one.

Thanks for working on Polymer, it's a wonderful project. 
Have a nice day, Jan

**Comment by notwaldorf** [comment]
The whole point of auto validation is to validate as you type (so that for example, if you should only type numbers, if you type a letter you get notified immediately)

What you want is an on-change event listener and call `validate` in it (so that you only validate when the element loses focus)

**Comment by honzabenes** [comment]
In my opinion the immediate validation is a bit aggressive (for example when user is filling in an email it gets annoying). But thanks for answer.
