### ISSUE TITLE
[ios] cursor displayed on top of paper-textarea placeholder

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/paper-input#468]
The cursor is displayed on top of the placeholder text when focusing on `paper-textarea`
https://beta.webcomponents.org/element/PolymerElements/paper-input/demo/demo/index.html
![paper-textarea](https://cloud.githubusercontent.com/assets/6173664/21276596/ff83adba-c386-11e6-8401-e3585787490f.gif)

@notwaldorf FYI

**Comment by notwaldorf** [comment]
Gah, this seems to be an iOD bug :sob: http://stackoverflow.com/questions/6890149/remove-3-pixels-in-ios-webkit-textarea

Looking to see if this `text-indent:-3px;` works, but I am suspicious about it

**Comment by notwaldorf** [comment]
Ok I think as a workaround, this should do:
```
paper-textarea {
      --iron-autogrow-textarea: {
        margin-left: -3px;
      }
    }
```
