### ISSUE TITLE
Implement documented step behavior: Binds to non-existent `step` on `iron-input`

### ISSUE THREAD

**Issue by kriscooke** [PolymerElements/paper-input#472]
### Description
The [step property](https://elements.polymer-project.org/elements/paper-input#property-step) for input type "number" as documented does nothing. PaperInputBehavior binds its `step` prop to `step` on `iron-input`, which (as far as I can tell) has never had a `step` property.

`paper-slider` gets its stepped behavior from IronRangeBehavior - has that ever been a behavior of paper-input / iron-input at any time in the past?

### Expected outcome

Set `step` to a value, change `value` to be somewhere in between two steps, and on change/loss of focus the input value should be rounded to the nearest step. Potentially `min` or `max` would need to be set in order to determine the step values.

### Actual outcome

The typed number remains the same, regardless of `step`.

### Live Demo
https://jsbin.com/gatiruyiti/edit?html,output

**Comment by notwaldorf** [comment]
The `step` property is a property of the native `input type="number` element (https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement). In the jsbin you linked to, in Chrome, press the up/down arrows at the right side of the input. You'll notice the value increases/decreases by 10 (the `step` you provided):
<img width="97" alt="screen shot 2017-01-04 at 5 23 29" src="https://cloud.githubusercontent.com/assets/1369170/21665750/9bbd89ec-d2a2-11e6-8d88-364246a5d78c.png">

The `step` attribute is only used by `type="number"`, and only when the up/down arrows are used, not when you set the value imperatively.

Closing, as this is working according to the HTML spec

**Comment by kriscooke** [comment]
Ah, thanks - I didn't realize that was a native attribute, that would explain why I couldn't find it in any of the behaviors! :man_facepalming:

**Comment by notwaldorf** [comment]
No worries! Glad this helped!
