### ISSUE TITLE
paper-input not loading in Firefox

### ISSUE THREAD

**Issue by jaichandra** [PolymerElements/paper-input#487]
### Description

Below is an example of custom elements where paper-input doesn't even render on Firefox.

Firefox version: 51.0.1 (64-bit)
OS: macOS Sierra 10.12.3
### Expected outcome

`paper-input` should render in the example

### Actual outcome
`paper-input` doesn't even load

### Live Demo

https://jsfiddle.net/kleptomac/v7kjyk7a/

### Browsers Affected

- [ ] Chrome
- [x] Firefox: 51.0.1 (64-bit)
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
You need to wrap your JS code in a `document.addEventListener('WebComponentsReady')`. The webcomponents polyfill loads the custom elements asynchronously, so you need to wait for that even before you can use it. 

Here's your example, updated and working: https://jsfiddle.net/wuu2dp1b/

**Comment by jaichandra** [comment]
Thanks @notwaldorf and apologies for missing out that part. Was going crazy with the other event-retargeting issue.
