### ISSUE TITLE
[2.0-preview] Label, placeholder and error-message not showing in Safari and Firefox

### ISSUE THREAD

**Issue by MTLcoder** [PolymerElements/paper-input#491]
### Description
I'm using the 2.0 preview version of Polymer Elements for my web app. As I'm testing on Chrome, everything works fine. However, when I switched to Firefox and Safari to check if everything is going good too I saw some glitches in the UI of the paper-input element.

### Expected outcome
I should be able to see the label/placeholder (with the floating label) and the error-message when the input is invalid.

### Actual outcome
Label/Placeholder should be visible and when the field is in the invalid state, the error-message does not show up. however, the line become red so at least this is working. But whenever I click on it, the label/placeholder appears and the behaviour is there. But not the error-message.

### Workaround
I found a workaround to make at least the label/placeholder do their thing. I use `.assignedNodes()` on the slot responsible for the label. This kind of 'awake' the inputs in Safari and Firefox. But the error-message still do not show up. But I can see in the Development Tools of Safari that it's value is there (when I asked the paper-input what is its `error-message`).

### Steps to reproduce
Put some paper-inputs from the 2.0 preview version and open your localhost with Safari and/or Firefox.

### Browsers Affected
- [ ] Chrome
- [x] Firefox
- [x] Safari 10
- [x] Safari iOS

### Not tested
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
This is really old, so I'm not sure it's still reproducible. This is what I see on FF right now, which looks correct:
<img width="320" alt="screen shot 2017-04-04 at 10 39 46" src="https://cloud.githubusercontent.com/assets/1369170/24670486/0ef35ccc-1923-11e7-948c-d428fc73defe.png">

Closing, but please reopen if you have some code reproducing the problem
