### ISSUE TITLE
paper-input-container does not work inside with polymer 2.0.0-rc.2

### ISSUE THREAD

**Issue by ErikGrimes** [PolymerElements/paper-input#494]
### Description
```
<link rel="import" href="../polymer/polymer.html">
<link rel="import" href="../paper-input/paper-input-container.html">
<link rel="import" href="../iron-input/iron-input.html">

<dom-module id="input-element">
  <template>
    <style>
      :host {
        display: block;
      }
    </style>
    <h2>Hello</h2>

    <paper-input-container>
      <label>label</label>
      <input is="iron-input">
    </paper-input-container>

  </template>

  <script>
    class InputElement extends Polymer.Element {
        static get is() {return 'input-element'}

        constructor(){
            super();
        }
        
    }

    window.customElements.define(InputElement.is, InputElement);

  </script>
</dom-module>
```

### Expected outcome

![expected](https://cloud.githubusercontent.com/assets/1533326/23920970/cdc340d6-08ca-11e7-83f0-444eb9bb65e1.png)

"label" should be displayed and it should be possible to enter input.

### Actual outcome

![actual](https://cloud.githubusercontent.com/assets/1533326/23920977/d5f9e6d8-08ca-11e7-805e-840afcf4c1db.png)

"label" is not displayed and you can't enter any input.

### Steps to reproduce

1. Put an `input-element` element in the page.
2. Run polymer serve with polymer-cli@next
3. Click the displayed input element

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Safari 10
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

### Notes
I tried the same thing under Polymer 2 using a Polymer 1 style host with the same result.  For some reason, paper-input works just fine. I also took the same Polymer 1 host, copied it into a Polymer 1 project and it worked fine.

**Comment by notwaldorf** [comment]
There are a bunch of problems going on: You need to use the right slot names for distribution (check the docs on the 2.0-preview branch; also, make sure you are using the 2.0-preview branch), and you need to use the 2.0-preview version of iron-input (is= is not supported in polymer 2)
