### ISSUE TITLE
Can't cancel preventInvalidInput when using allowedPattern

### ISSUE THREAD

**Issue by fabiomolinar** [PolymerElements/paper-input#496]
### Description

I am using the following RegEx to validate an input: `/^[+]?([0-9]+(?:[\.][0-9]*)?|\.[0-9]+)$/`. That regex should accept any positive number (**including decimals**). The problem I have is that when I want to type a decimal number, the automatic preventInvalidInput don't allow me to start typing the decimal number. That is, I can't type `2.` because this string don't match the regex. But `2.1` does. So, I am blocked from typing decimal numbers because I can't type anything that matches `<integer>.`.

If I `ctrl+c` a decimal number (with `.`, like `2.1`), then I am able to `ctrl+v` it inside the `<input>`. Not the best UX, right?

### Expected outcome

When using regex with the allowedPattern property, I want to be able to stop the automatic validation.

### Actual outcome

I can't type decimal numbers because I am not allowed to enter a point after a number (the intermediate step before getting to type any decimal number.

### Steps to reproduce
Just add the following property to a `<paper-input>`: `allowed-pattern="^[+]?([0-9]+(?:[\.][0-9]*)?|\.[0-9]+)$"`

**Comment by notwaldorf** [comment]
You want to use that regex in `pattern`, not `allowed-pattern`. The latter is explicitely used for preventing invalid input. :)
