### ISSUE TITLE
[2.0-preview] paper-input demo snippets don't work

### ISSUE THREAD

**Issue by Trolleule** [PolymerElements/paper-input#497]
### Description
I did a quick start with polymer init (starterkit), installed paper-input#2.0-preview and added some of these demo snippets for example:

    <paper-input label="total" type="number">
      <div prefix>$</div>
    </paper-input>
    <paper-input label="username" id="inputWithButton">
      <iron-icon icon="mail" prefix></iron-icon>
      <div suffix>@email.com</div>
      <paper-icon-button suffix onclick="clearInput()" icon="clear" alt="clear" title="clear">
      </paper-icon-button>
    </paper-input>

the output is not the same, as expected.

### Expected outcome

Its not looking like demo.

### Actual outcome

The input field should appear next to each other with icons in it and suffixes but instead they are among each other and have no icons

### Live Demo
https://www.webcomponents.org/element/PolymerElements/paper-input/demo/demo/index.html

### Steps to reproduce

Can somone commit this?
And I think its not the only broken webcomponent :/

### Browsers Affected

- [ x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
In 2.0, the shadow DOM spec changed so you need to specify the slot on the suffix -- it needs to be `<div slot=prefix>`. Please check the docs or the 2.0-preview demo for the exact details.
