### ISSUE TITLE
Add mixin for ::-ms-clear pseudo-element

### ISSUE THREAD

**Issue by z2oh** [PolymerElements/paper-input#501]
IE automatically adds a clear button to text inputs. We are using a custom clear button to enable this functionality in other browsers, and would like to use our clear button in IE as well (it has additional functionality compared to the one IE inserts).

Microsoft provides a CSS pseudo-element [::-ms-clear](https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-clear) to style this clear button, and the common way to hide it is to use the following CSS:

```
::-ms-clear {
    display: none;
    width: 0px;
    height: 0px;
}
```

I was able to hide the clear button with the following:

```
<style>
#input::shadow input::-ms-clear {
    display: none;
    width: 0;
    height: 0;
}
</style>
<div>
...
<paper-input id="input"></paper-input>
...
</div>
```

but since the ::shadow pseudo-element is deprecated I want to avoid using it. This can be fixed by adding a CSS mixin. Is there another, simpler solution that I'm missing? If not, I would be happy to open a PR adding the mixin if there is any interest from the devs.

**Comment by notwaldorf** [comment]
Sounds good! Here's a similar PR that adds something for the spinner: https://github.com/PolymerElements/paper-input/pull/495

**Comment by ShaggyDude** [comment]
We need the same thing for ::-ms-reveal I will open a merge rquest
