### ISSUE TITLE
--paper-input-container-input : setting border and margin produces 2 border boxes

### ISSUE THREAD

**Issue by thomasvogel** [PolymerElements/paper-input#504]
#expected outcome of the below code: 
a red box is rendered around the inner input of paper-input(s)

#actual outcome:
two red boxes are rendered

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1, initial-scale=1, user-scalable=yes">

    <title>error demo</title>

    <script src="../../webcomponentsjs/webcomponents-lite.js"></script>

    <link rel="import" href="../../iron-demo-helpers/demo-pages-shared-styles.html">
    <link rel="import" href="../../iron-demo-helpers/demo-snippet.html">
    <link rel="import" href="../../paper-input/paper-input.html">

    <custom-style>
        <style include="demo-pages-shared-styles">
            html {
                --paper-input-container-input: {
                    box-sizing: border-box;
                    margin-top: 10px;
                    border: 1px solid red;
                }
                ;
            }

        </style>
    </custom-style>
</head>

<body>
    <div class="vertical-section-container centered">
        <h3>paper-input mixin problem</h3>
        <demo-snippet>
            <template>
                <paper-input></paper-input>
            </template>
        </demo-snippet>
    </div>
</body>

</html>

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
Argh, good catch. Thanks!

**Comment by notwaldorf** [comment]
fixed in 69d58c9
