### ISSUE TITLE
Way to manually set highlight (focused)

### ISSUE THREAD

**Issue by rene-lindner-isw** [PolymerElements/paper-input#507]
### Description Part 1
There is currently no way to manually highlight an paper-input, it's only possible via focus.
But in some use cases the paper-input will loose focus, while it's still active and should be highlighted.

e.g. An paper-dropdown-menu with opened dropdown.

### Expected outcome
The paper-dropdown-menu's paper-input should be highlighted.

### Actual outcome
The paper-dropdown-menu's paper-input is not highlighted.

### Description Part 2
Since the paper-input cannot be highlighted manually, theres no way to implement this in the paper-dropdown-menu. I've implemented an dropdown-menu with multi-select, and also have no way to highlight the paper-input if the dropdown is open.

https://github.com/rene-lindner-isw/isw-dropdown-menu/issues/2

https://www.webcomponents.org/element/rene-lindner-isw/isw-dropdown-menu/demo/demo/index.html

### Proposal
Introduce an new Boolean property (e.g. highlight).
Introduce an new computed Boolean property (e.g. _displayFocused)

The focused display is bound to the computed property, which is true if either focused or highlight is true.

### Live Demo
https://www.webcomponents.org/element/PolymerElements/paper-dropdown-menu/demo/demo/index.html

### Browsers Affected
Every Browser.

**Comment by notwaldorf** [comment]
I think this is very bad for a11y -- things should look focused _only_ when they are focused. Otherwise, if it looks focused and someone starts typing in it, no text will appear. 

You can style the default state of the input to be blue (using custom properties), but if it's not different than your actually-focused state, you will make your users sad :(

**Comment by rene-lindner-isw** [comment]
I'm not talking about making a normal paper-input look like focused to confuse people.

I'm talking for example about an open paper-dropdown-menu - where the whole paper-dropdown-menu is focused - but it's paper-input child cannot display that it's parent is focused.

**Comment by rene-lindner-isw** [comment]
Just saw - the light version works. The normal version not.

https://www.webcomponents.org/element/PolymerElements/paper-dropdown-menu/demo/demo/index.html
