### ISSUE TITLE
paper-input#2.0-preview can't input chinese and the input order is reversed

### ISSUE THREAD

**Issue by kevinpschaaf** [PolymerElements/paper-input#509]
_From @woshimanong1990 on April 5, 2017 7:39_

The issue is just for 2.0,the 1.0 work well.

_Copied from original issue: Polymer/polymer#4499_

**Comment by kevinpschaaf** [comment]
@woshimanong1990 Please post a reproduction, e.g. [jsBin](http://jsbin.com/?html,output).

**Comment by notwaldorf** [comment]
Not sure I can repro. Using the [demo](http://polygit.org/polymer+v2.0.0-rc.3/webcomponentsjs+webcomponents+v1.0.0-rc.6/shadycss+webcomponents+1.0.0-rc.2/paper*+polymerelements+:2.0-preview/iron*+polymerelements+:2.0-preview/app*+polymerelements+:2.0-preview/neon*+polymerelements+:2.0-preview/components/paper-input/demo/index.html) I tried entering characters with the "Zhuyin" keyboard on desktop, and they are entered RTL

**Comment by notwaldorf** [comment]
Hmm, though I tried the traditional chinese keyboard on my iPhone and the 2.0 input behaves indeed differently than in 1.0 (it doesn't wait for a character to be ready, it just inserts all the intermediate radicals) :(

**Comment by woshimanong1990** [comment]
Sorry,I don't know how to import the paper-input components.Now the order of the characters is right,but I can't get the right chinese characters.For example,if I want to get '中国',I will input 'zhongguo'.Normally,the IME will translate it to '中国' or something,but It does not happend. It is just 'zhongguo'.
the


At 2017-04-11 01:50:55, "Kevin Schaaf" <notifications@github.com> wrote:


@woshimanong1990 Please post a reproduction, e.g. jsBin.

**Comment by notwaldorf** [comment]
@woshimanong1990  i've pushed an update to `iron-input`, where the underlying bug was, which i think should help. Let me know if you still repro this!

**Comment by woshimanong1990** [comment]
Thanks！It's ok now!





At 2017-04-12 05:36:49, "Monica Dinculescu" <notifications@github.com> wrote:


@woshimanong1990 i've pushed an update to iron-input, where the underlying bug was, which i think should help. Let me know if you still repro this!
