### ISSUE TITLE
updateLabelVisibility() missing...?

### ISSUE THREAD

**Issue by firasdib** [PolymerElements/paper-input#51]
Hello,

In polymer 0.5 you could clear the values of an input and then call `updateLabelVisibility()` to have the label float back to its original position. I can't find a way of doing this in polymer 0.9. Any suggestion on how to do this or perhaps re-implement the old function?

Thanks.

**Comment by morethanreal** [comment]
If you're using a `<paper-input>`, the label should auto update when you set `value`. If you're using a `<paper-input-container>` and `<input is="iron-input">`, set the `iron-input`'s `bindValue`.

ie.
```html
<paper-input id="paperInput" label="foo" value="bar"></paper-input>
<paper-input-container id="paperInputContainer" label="foo">
  <input is="iron-input" id="input" bind-value="bar">
</paper-input-container>
```

```js
this.$.paperInput.value = '';
this.$.input.bindValue = '';
```

**Comment by firasdib** [comment]
Thank you, that worked flawlessly!
