### ISSUE TITLE
paper-textarea rows makes maxRows malfunction

### ISSUE THREAD

**Issue by seventhmoon** [PolymerElements/paper-input#512]
### Description
`paper-textarea`  `maxRows` malfunction after `rows` is set.

`       <paper-textarea label="Postal Address" required  rows="3"  maxRows="4">`

### Expected outcome
Initial row count = 3, max row is 4

### Actual outcome
Initial row count = 3, max row is unlimited

### Live Demo
N/A

### Steps to reproduce
1. Create a `paper-textarea` element with `maxRows` set (working)

`    <paper-textarea label="Postal Address" required maxRows="4">`

2. insert `rows` to setup initial size (`rows` work, but `maxRows` fails`)

`   <paper-textarea label="Postal Address" required  rows="3"  maxRows="4">`

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
This should be `max-rows`, not `maxRows`
