### ISSUE TITLE
failed to input Chinese characters in paper-input#2.0-preview with IME

### ISSUE THREAD

**Issue by mindon** [PolymerElements/paper-input#514]
### Description

Cannot input Chinese (using pinyin IME) using the `paper-input` element - the input panel flash out immediately in Chrome and the mass input in Safari, it works fine in Firefox Developer Edition, and it works fine using `paper-textarea`.

### Expected outcome
value="**测试**"

### Actual outcome

value="**ceshi** " (Chrome)

value="**测试ce shice shice shce shce sce scececc**" (Safari)

### Live Demo

`
  <paper-input label="IME failed in paper-input"></paper-input>
  <paper-textarea label="IME ok in paper-textarea"></paper-textarea>
`

Failed in **Chrome**

![Chrome canary](http://fanglet.com/wp-content/uploads/2017/04/chrome-paper-input-ime-issue-demo.gif)

Failed in **Safari**

![Safari 10](http://fanglet.com/wp-content/uploads/2017/04/safari-paper-input-ime-issue-demo.gif)

It should be (Firefox DevEdtion)

![Firefox Dev Edition](http://fanglet.com/wp-content/uploads/2017/04/firefox-paper-input-ime-issue-demo.gif)

### Steps to reproduce

1. Put a `paper-input` element in the page.
2. Open the page in Chrome or Safari.
3. Focus the `paper-input` element.
4. Switch to an IME (such as Pinyin Input Method <http://pinyin.google.com/> )
5. Try to input "ceshi" (which should display IME panel showing "测试" ...)

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [x] Safari 10
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
I recently fixed this in `iron-input`, so if you run a `bower install` again, you should pick up the new version. Also, I don't think I can repro this in the latest version: http://jsbin.com/wizodul/edit?html,output (I'm using the "Zhuyin" keyboard on the mac)

**Comment by mindon** [comment]
the updates works perfect on polymer#2.0.0-rc.6, thanks a lot
