### ISSUE TITLE
Paper-input 2.0 preview not showing the prefix and suffix elements

### ISSUE THREAD

**Issue by stackt52** [PolymerElements/paper-input#515]
I was trying to implement a `paper-input` with  `prefix` and `suffix` elements under Polymer 2.0 but that doesn't seem to work. That worked just fine under Polymer 1.x with `PolymerElements/paper-elements#^1.x`, but when I upgraded my app's dependencies to Polymer 2.0 and `paper-input#2.0-preview` both `prefix` and `suffix` elements stopped showing on the `paper-input`. I really need them to show for my app's user interaction friendliness.

**Comment by web-padawan** [comment]
Have you replaced `prefix` with `slot="prefix"`?

**Comment by stackt52** [comment]
Awesome!! it now works
