### ISSUE TITLE
2.0-preview type=email cursor jump

### ISSUE THREAD

**Issue by ackushiw** [PolymerElements/paper-input#517]
### Description

When editing somewhere in the middle of the text in the input the cursor jumps to the end of the text.

### Steps to reproduce
1. Add `type="email"` to `paper-input` in your page.
2. Open the page in a web browser.
3. Type in the `paper-input` element.
4. Edit your text somewhere in the middle.

### Browsers Affected

- [x] Chrome
- [x] Chrome Canary
- [ ] Firefox
- [ ] Safari 10
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
I can't reproduce this: http://output.jsbin.com/neyota
This was broken on an earlier version (early last week, maybe), but it's been fixed since. Please re-open this if you have a repro jsbin.
