### ISSUE TITLE
paper-input#2.0-preview stays focused on IE and Safari

### ISSUE THREAD

**Issue by Geoffrey-Pliez** [PolymerElements/paper-input#524]
### Description

Example:
<paper-input always-float-label label="Floating label"></paper-input>
        <paper-input label="username
            <iron-icon icon="mail" prefix></iron-icon>
            <div suffix>@email.com</div>
        </paper-input>

When I try to complete the 2 paper-inputs, the first paper-input stays focused and it's impossible to fill the second paper-input.

on IE,  focus moves from one to the other continuously and IE Freeze

### Expected outcome
Focus changes

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [ ] Edge
- [x] IE 11
- [x] IE 10

**Comment by notwaldorf** [comment]
Good call! Fixed in 168bdf0, thanks!
