### ISSUE TITLE
Label not floating in paper-input-container

### ISSUE THREAD

**Issue by tdesc** [PolymerElements/paper-input#53]
Simple container with input and label. Expected behaviour that label will be float. It's not
Chrome desktop browser latest version.
```
    <paper-input-container>
        <label>Your name</label>
        <input is="iron-input">
    </paper-input-container>
```

**Comment by notwaldorf** [comment]
The label should float once you start typing (but not initially). If you want it to float initially, you need to add the `always-float-label` attribute to the `paper-input-container`.

I've tried it both on Canary and Chrome stable, and it seems to work. Are you sure you're including all of the right things (`paper-input-container`, `iron-input`)?

**Comment by tdesc** [comment]
paper-input works as expected. example as I wrote above dont.
Chrome MacOS version 43.0.2357.81 (64-bit)

**Comment by notwaldorf** [comment]
Hmm, I'm not sure what you mean. Here is some code, in a jsbin: http://jsbin.com/cuqulajuto/3/edit.

The labels work fine in Chrome 43, Safari and Firefox. You're right that the char counter has a problem in Safari, and we're looking into that.

**Comment by notwaldorf** [comment]
The remaining char-counter issue was fixed in https://github.com/PolymerElements/paper-input/pull/78

**Comment by mixedCase** [comment]
I feel like I should add for the people googling this issue: if the label is not floating automatically it's very likely that you have not HTML imported iron-input.
