### ISSUE TITLE
allow flex-wrap styling of input-content div

### ISSUE THREAD

**Issue by mkropf** [PolymerElements/paper-input#535]
### Description
We have a case where we have several longer prefix elements, unfortunately we can't find a way to style the input-content div so that it wraps the prefix elements. Would it be possible to add a mixin to that div so that it can be styled? Other Idea?

**Comment by notwaldorf** [comment]
Hmm, can you show me an example for what do you mean by "wraps the prefix elements"? There's a request to add a mixing to `input-content` (yours) and a different one for `input-wrapper` and i'd like to see if they can be combined, or if there's a workaround to not add either (they're pretty drilled down, and as a rule we'd prefer not to add mixins for like...every div in the element)

**Comment by mkropf** [comment]
I was in the early learning curve back then and have found easy workarounds since. Sorry I didn't close the issue
