### ISSUE TITLE
Attribute-binding for 'required' does not cause style to be applied

### ISSUE THREAD

**Issue by dstefanox** [PolymerElements/paper-input#551]
### Description
Style is defined for paper-input element which has 'required' attribute:
`  paper-input[required] {
    --paper-input-container-label: {
      color: green;
    }
    ;
    --paper-input-container-label-floating: {
      font-weight: bold;
      color: green;
    }
    ;
    --paper-input-container-underline: {
      border-bottom: 2px solid green;
    }
  }`
Attribute is set via attribute-binding:
`<paper-input required$="[[isRequired]]" label="Required attribute-binging"></paper-input>`

Style is not applied, although element behavior is as expected regarding required attribute. 

### Expected outcome
When 'required' attribute is set, appropriate style of the element is set. 

### Actual outcome
When 'required' attribute is set via attribute binding, style is not applied. When it is set without binding, it gets applied:
`<paper-input required label="Required without attribute-binding"></paper-input>`

### Live Demo
Example on jsfiddle:
https://jsfiddle.net/dstefanox/h6xz9usn/3/

Example illustrates all mentioned aspects - setting required via attribute-binding does not work, directly works. Also, example shows that attribute-binding works as expected for 'disabled' attribute.

### Steps to reproduce
1. Define special style for paper-input when having required attribute ( paper-input[required])
2. Bind 'required' attribute to boolean variable (required$="[[isRequired]]") in paper-input. Style is not applied
3. Set 'required' attribute directly in paper-input. Style is applied as expected.

### Browsers Affected
Tried in following two.
- [ *] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [* ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
I think this is the CSS shim limitation: https://www.polymer-project.org/2.0/docs/devguide/custom-css-properties#custom-properties-shim-limitations
You can't update the values of mixins dynamically without calling `updateStyles`

**Comment by dstefanox** [comment]
You are right, using updateStyles after setting attribute actually did solved the problem. Thanks for support. I assume it is OK to close this issue now, so I will do it.
