### ISSUE TITLE
Readonly is not settable

### ISSUE THREAD

**Issue by phidias51** [PolymerElements/paper-input#558]
The readonly attribute doesn't seem to be settable.

In this example, I have a paper-input that should only be editable if you have an "editor" role in your profile.

```
<paper-input label="Something" value="{{something}}" readonly="[[isNotEditor]]"></paper-input>

```

The problem is I can set the flag to either true or false, and it makes no difference. The field is always readonly.  It seems to assume that if the readonly attribute appears then it is always true.

**Comment by andrewspy** [comment]
@phidias51 Have you tried using [attribute binding](https://www.polymer-project.org/1.0/docs/devguide/data-system#data-bindings)? i.e.

```html
<paper-input label="Something" value="{{something}}" readonly$="[[isNotEditor]]"></paper-input>
```

**Comment by phidias51** [comment]
I can understand the need to do that with native components but why would
you need to do that for a polymer component?

**Comment by andrewspy** [comment]
I think there is some different between setting attribute and setting property for a webcomponent. One of the reason of setting the attribute is that CSS will be able to "see" the standard attribute, but not the propery, i.e.

```css
paper-input[readonly] {
}
```

**Comment by web-padawan** [comment]
Have a look at the code: the [readonly](https://github.com/PolymerElements/paper-input/blob/master/paper-input-behavior.html#L285) property does not have `reflectToAttruibute: true`, therefore you have to manually force attribute to appear via attribute binding.

The reason for this is likely the fact that Material Design spec for [text fields](https://material.io/guidelines/components/text-fields.html#text-fields-states) prefers `disabled` state for styling not editable input fields, and read-only state seems to bejust the one particular case here.

**Comment by notwaldorf** [comment]
Yup, `readonly` is not reflected, so it will not work for styling. Is there a reason why `disabled` doesn't work? We do a bit of extra work (like setting`pointer-events:none`) other than just styling, so I'd recommend using that.

**Comment by andrewspy** [comment]
There are situation where I need the paper-input to be readonly, without disabling it completely. One of the use case is in a check-in/check-out situation, where user can input check-in info while checking in, and during check-out process, the check-in info is still relevant but I need to prevent user from editing it (with readonly).

Disabling the check-in info completely in this case just doesn't make sense.
