### ISSUE TITLE
Paper input not binding to value in  PSK app updated to 2.0

### ISSUE THREAD

**Issue by bennypowers** [PolymerElements/paper-input#567]
I can enter text into the paper input, but the label doesn't float until I blur the input.

When I inspect the paper-input element, it's `value` is empty, although if I inspect the paper-input's internal `input` element, it has a `value`

![paper-input](https://user-images.githubusercontent.com/1466420/30217417-bfc7693c-94be-11e7-91aa-fcb871d9bbd3.gif)

This code works in jsbin, but not in my updated polymer1.6-era psk app
https://jsbin.com/yerucoqara/1/edit?html,console,output

This is broken in chrome, safari, and firefox, and I get no console errors

```
$0.value
""
$0.$.input.value
"fda"
```
where $0 == paper-input

**Comment by chisholmd** [comment]
I am experiencing the same problem, its kind of a massive show stopper.
Is there any work being done on this?

**Comment by notwaldorf** [comment]
that JSBin works fine for me on Chrome:
![test](https://user-images.githubusercontent.com/1369170/30881307-3a1ef930-a2ba-11e7-8512-955f2726d7de.gif)

Are there any other details to repro?

**Comment by chisholmd** [comment]
Ugh...somehow I had a paper-input from 2015.

**Comment by notwaldorf** [comment]
Oh, that's definitely not the right one!

Closing then, as I can't repro with the jsbin given :)
