### ISSUE TITLE
Help with [add-on] autocomplete implementation

### ISSUE THREAD

**Issue by tdesc** [PolymerElements/paper-input#57]
Please give some tips, how to implement "autocomplete" add-on for paper-input-container.
It need 'focus/blur' event and change event.
Change event behaviour is close to paper-input-char-counter, but I didn't found any focus/blur listeners example.

**Comment by notwaldorf** [comment]
`focus`, `blur`, `change` are events now available for `paper-input`, but not for add-ons. I am not super sure you want to do this as an add-on -- add-ons only have access to the input's value, and pretty much nothing else :(

**Comment by notwaldorf** [comment]
@samccone has a `paper-typeahead` element here, that might be useful to you: https://github.com/samccone/paper-typeahead

**Comment by samccone** [comment]
http://samccone.github.io/paper-typeahead/components/paper-typeahead/

full docs and demo now :sparkles: 

thanks for the ping @notwaldorf :hand:
