### ISSUE TITLE
IE11 - The First paper-input on the Page Renders Incorrectly

### ISSUE THREAD

**Issue by brainmonger** [PolymerElements/paper-input#575]
### Description
IE11 - The first paper-input on the page renders incorrectly.

### Expected outcome
The first paper-input on the page should render without the defects listed below.

### Actual outcome
IE11 - The first paper-input on the page renders with the following noticeable defects:
1. down/arrow is defaulting as red color.
2. selected value is displaying in red color.
3. the horizontal line is displaying as blue by default.

Note: If you duplicate the element, the subsequent element renders correctly without issues. The problem is only with the first element on the page.

### Live Demo
in progress - will add

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [x] IE 11
- [ ] IE 10

**Comment by brainmonger** [comment]
Closing for now. I do think it's an IE11 specific issue but we are calling paper-input from another custom element with some added CSS so I think it might be a little complicated to provide you a demo. I'll reopen if am able to put aside some time to wire up a comparable demo for this.

**Comment by notwaldorf** [comment]
It sounds (to me) like it's not a paper-input issue, but some sort of custom properties issue. I'd look at anything that sends a custom property (maybe dynamically), and seeing if it gets fixed if you call `updateStyles`. Good luck!
