### ISSUE TITLE
[1.0] Floating label is positioned incorrectly when RTL is enabled

### ISSUE THREAD

**Issue by dzhioev** [PolymerElements/paper-input#58]
See demo http://dzhioev.net:8080/arabic_input.html

**Comment by morethanreal** [comment]
Need https://github.com/Polymer/polymer/commit/94daa17ad991bc5627d8bc6626e07bbd89a527c8 to land in a Polymer release before I can fix this.

**Comment by morethanreal** [comment]
Whoops, spoke too soon with the previous comment. @notwaldorf can you also fix this when the rtl behavior is landed?

The `transform-origin` in https://github.com/PolymerElements/paper-input/blob/master/paper-input-container.html#L164 and https://github.com/PolymerElements/paper-input/blob/master/paper-input-container.html#L165 needs to be `right top` if it's rtl.

**Comment by MWalid** [comment]
Any updates with this one?

**Comment by notwaldorf** [comment]
I'll look at it next week! Sorry!

**Comment by notwaldorf** [comment]
Fixed in https://github.com/PolymerElements/paper-input/pull/220 :tada:
