### ISSUE TITLE
Cannot style the inner textarea of a paper-textarea

### ISSUE THREAD

**Issue by think01** [PolymerElements/paper-input#589]
### Description

I'm unable to style the HTML element textarea inside a paper-textarea.
I need the inner textarea to have the css style: 
```
box-sizing: border-box;
```
I tried several styling ways, for example:
```
      :host,
      paper-textarea,
      paper-input-container {
        --paper-input-container-input: {
          box-sizing: border-box;
        }
      }
```
or
```
      iron-autogrow-textarea {
        --iron-autogrow-textarea: {
          box-sizing: border-box;
        };
      }
```

### Expected outcome

The inner textarea element must have the css style: 
```
box-sizing: border-box;
```

### Actual outcome

The textarea element doesn't receive the new style (and my layout gets broken).

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
Here's a demo of styling the inner textarea: http://jsbin.com/fezafih/1/edit?html,output

Closing, as there's no repro steps provided

**Comment by think01** [comment]
Well, I showed what code wasn't working, I assumed it was good for repro steps.
Anyway, your example is exactly what I was looking for and it resolved my issue, thank you so much!
