### ISSUE TITLE
[0.9] event on-blur does not work on paper-input

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-input#59]
<paper-input id="email" name="email" label="Email" error-message="Email is required" on-blur="inputBlur" required floatinglabel layout vertical>             
</paper-input>

**Comment by zhaoz** [comment]
+1 to this bug, hit it today.

**Comment by kirilledelman** [comment]
on-focus doesn't work either.

**Comment by Nick-Ewer** [comment]
on-key-up doesn't seem to work either (1.0.1)

**Comment by morethanreal** [comment]
`focus` and `blur` are re-dispatched in shady dom.
