### ISSUE TITLE
style issue in v2.0.4

### ISSUE THREAD

**Issue by AliMD** [PolymerElements/paper-input#597]
### Description
The `paper-input` element display incorrently in inline-block mode!

### Expected outcome
![screen shot 2017-12-05 at 12 30 56 pm](https://user-images.githubusercontent.com/697913/33598506-4aa47bf6-d9b8-11e7-8669-bbc63b69aaaf.png)

### Actual outcome
![screen shot 2017-12-05 at 12 31 21 pm](https://user-images.githubusercontent.com/697913/33598509-4f0c4e58-d9b8-11e7-855f-cbdd3cedacb5.png)

### Live Demo
- [Demo of v2.0.3](https://jsbin.com/fonupur/3/edit?html,output)
- [Demo of v2.0.4](https://jsbin.com/fonupur/5/edit?html,output)

### Browsers Affected

- [x] Chrome

I don't check other browsers

**Comment by AliMD** [comment]
@notwaldorfI think its about your last commit
We use this component in production mode could you please fix it as soon as possible?
Otherwise, we force new hotfix and fix bower to v2.0.3 😞

**Comment by AliMD** [comment]
@notwaldorf think its about your last commits
We use this component in production mode could you please fix it as soon as possible?
Otherwise, we force new hotfix and fix bower to v2.0.3 😞

**Comment by notwaldorf** [comment]
Trying!

**Comment by AliMD** [comment]
@notwaldorf issue solve confirm, thank you
