### ISSUE TITLE
[1.0] A way to programmatically focus paper-input is needed

### ISSUE THREAD

**Issue by dzhioev** [PolymerElements/paper-input#60]
As far as I understand there is no way to focus <paper-input> from JS.
I tried <paper-input>.focus() but it doesn't work.
I even tried to focus the inner <input> from DevTools, but it doesn't work as well.

**Comment by morethanreal** [comment]
Try `$.inputElement.focus()`?

**Comment by dzhioev** [comment]
@morethanreal, sorry, I didn't know that GitHub removes `<tags>` without quotes.
My original message was supposed to be:
> As far as I understand there is no way to focus `<paper-input>` from JS.
> I tried `<paper-input>`.focus() but it doesn't work.
> I even tried to focus the inner `<input>` from DevTools, but it doesn't work as well.

So, no, focusing `inputElement` doesn't work. My browser is Chrome 42.0.2311.153 (Official Build) (64-bit).

**Comment by morethanreal** [comment]
The `inputElement` getter on `<paper-input>` returns the actual input element, so if `this` is the `<paper-input>`, you can call `this.$.inputElement.focus()` to focus the element. It is intentional that the element does not facade every API from the internal input element.

**Comment by dzhioev** [comment]
Sorry, my fault. I tried to focus an input from Chrome DevTools console. Turned out that is not possible, because focused doesn't leave the console. =)
