### ISSUE TITLE
[1.0] Should have more complete set of custom properties

### ISSUE THREAD

**Issue by kbwatts** [PolymerElements/paper-input#61]
`<paper-input-container>` has `--paper-input-container-color` to control styling for the label and underline color together - but probably it should be possible to control label and underline separately simply by using custom properties?

**Comment by morethanreal** [comment]
Perhaps! I chose the current set of variables because it seems the design intention is to have the label and underline colors match, and it's more convenient to only define one variable for this.

The label and underline don't have mixin hooks for if you really want to override their styles, and I can add them.

**Comment by kbwatts** [comment]
I absolutely understand that - and I agree that the Material Design spec up to this point seems to be pretty consistent about that in that these colours ought to match... but when I look at the search input in Google Music, Inbox, Developers (e.g. https://developers.google.com/), all of which are more or less material design, they don't make sure of the underline at all and instead opt for more of an input box, and indeed for our projects we'd want to aim for those looks to slowly transition people into the new design language over time.

All that to say, if you can add them, that would be amazing. Then we'd still get all the benefits that the element provides in terms of utility functions and things.

**Comment by kbwatts** [comment]
Also noticing the custom properties affecting the cursor and underline also affect the text colour, whereas the material design spec seems to keep text colour and floating label colour as `--primary-text-color` rather than an accent or default colour.

E.g. from MD spec:
![screen shot 2015-06-23 at 9 26 07 am](https://cloud.githubusercontent.com/assets/961706/8295690/83496e58-198a-11e5-8177-5ad42b9e72f7.png)

**Comment by morethanreal** [comment]
@kbwatts Do you have a link where the screenshot came from? In https://www.google.com/design/spec/components/text-fields.html#text-fields-floating-labels, the "focus" state has the floating label match the color of the line.

**Comment by kbwatts** [comment]
@morethanreal That screenshot came from the stickersheets provided here https://www.google.com/design/spec/resources/sticker-sheets-icons.html - though even looking at the MD spec in the url you sent, the very bottom "Full-width text field in app bar" style can best be achieved by making the underline transparent, right?

**Comment by morethanreal** [comment]
Hmm, the spec seems inconsistent on this issue. @zgibson ?

The full-width looks like a regular unstyled `<input>` to me.

**Comment by kbwatts** [comment]
It does look like a regular unstyled `<input>` to me also.

The issue with that is that anyone implementing the "Full-width text field in app bar" (for example) should probably use the same `<paper-input>` element so that (1) input values are saved even when resizing the viewport, and (2) functionality that handles the input won't need to be rewritten for both `<paper-input>` and `<input>`.

Please suggest if you have a better way of doing that :)
