### ISSUE TITLE
Once the Paper-input disabled and enabled border is coming outside input field

### ISSUE THREAD

**Issue by basavaraj4631** [PolymerElements/paper-input#619]
### Description
Programmatically disable the paper-input element 
for ex: this.$.inputField.disabled = true;
this.$.inputField.disabled = false;

click on input fields
border is coming outside the paper-input field.

### Expected outcome
blue border should not come when we click on paper-input field

### Actual outcome
blue border is coming only after disable and enable the input field

### Steps to reproduce
Add button 
disable and enable paper-input Programmatically 
click on paper-input field

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10
- [x] Nodewebkit

**Comment by notwaldorf** [comment]
I can't reproduce this: http://jsbin.com/sagucol/1/edit?html,output. You can't click on a disabled input in any way:

<img width="260" alt="screen shot 2018-02-20 at 10 59 59 am" src="https://user-images.githubusercontent.com/1369170/36443322-428a711c-162d-11e8-8599-c933e09c28a1.png">

I've also tried this in Firefox, to make sure it works under the polyfill, and it works the same way. Please post a JSBIn with reproducible steps, or else there isn't much I can look into :(
