### ISSUE TITLE
Element catalog doesn't have paper-input's document

### ISSUE THREAD

**Issue by shibukawa** [PolymerElements/paper-input#63]
https://elements.polymer-project.org/elements/paper-input

It includes paper-textarea, paper-input-container, paper-input-error, paper-input-char-counter document, but it doesn't have document of paper-input itself.

I can access demo page by typing URL directly, but the above document page doesn't have demo page link too. 

https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html&active=paper-textarea

**Comment by morethanreal** [comment]
It's a catalog bug: https://github.com/Polymer/polymer-element-catalog/issues/77
