### ISSUE TITLE
Default value used to be empty string and is now undefined.

### ISSUE THREAD

**Issue by notwaldorf** [PolymerElements/paper-input#633]
Last `paper-input` 1.x release: https://raw-dot-custom-elements.appspot.com/PolymerElements/paper-input/v1.1.24/paper-input/demo/index.html
If you inspect the first `paper-input`, its value is `""`

Current `paper-input` 2.x with Polymer 1: http://jsbin.com/vuhidof/edit?html
If you inspect the first `paper-input`, its value is `undefined`

**Comment by notwaldorf** [comment]
I think the suspect is actually `iron-input`:

`iron-input` 1.0.11 demo: https://raw-dot-custom-elements.appspot.com/PolymerElements/iron-input/v1.0.11/iron-input/demo/index.html
Default value is `""`

`iron-input` 2.1.2 demo: https://raw-dot-custom-elements.appspot.com/PolymerElements/iron-input/v2.1.2/iron-input/demo/index.html
Default value is `undefined`.

**Comment by freshp86** [comment]
Should we move this bug over to iron-input? Also is there any candidate fix?

**Comment by notwaldorf** [comment]
I haven't got a chance to look into it yet. Hoping to this week.

**Comment by notwaldorf** [comment]
This issue was moved to PolymerElements/iron-input#129
