### ISSUE TITLE
Redundant span elements around prefix&suffix causes only issues

### ISSUE THREAD

**Issue by kenyerr** [PolymerElements/paper-input#635]
When the Polymer 1->2 migration has been done, the prefix and suffix slots got wrapper span elements. ([here](https://github.com/PolymerElements/paper-input/commit/5bf54645cd7ae7a2558c398d2504f2cfcd1f054e#diff-a9a2db156d9736c00b0125ad8fa7de30R335))

This wrapping breaks at least the previously applied [fix](https://github.com/PolymerElements/paper-input/pull/303/commits/f5e467b9fcec5931ab1759fbc0a8763169c7252b) with [--layout-flex-none](https://github.com/PolymerElements/paper-input/commit/5bf54645cd7ae7a2558c398d2504f2cfcd1f054e#diff-a9a2db156d9736c00b0125ad8fa7de30R298) because it should be used on the wrapper element.

I have seen no benefit in using such span elements around so I would recommend to remove them and adjust the style accordingly, like:
```
.suffix::slotted(*)
...
<slot class="suffix" name="suffix"></slot>
...
```

**Comment by notwaldorf** [comment]
Unfortunately, this is needed because of the shady CSS shim (see the "Note" in the https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#style-slotted-content-distributed-children chapter)

**Comment by kenyerr** [comment]
I have just realized that the input-wrapper does not provide the split point which we would need to differentiate between the for example the prefix and suffix but what if we move the class="suffix" from the span element to the slot suffix and then use .suffix::slotted ?
