### ISSUE TITLE
TypeScript error with iron-form-element-behavior 2.1.2

### ISSUE THREAD

**Issue by qqilihq** [PolymerElements/paper-input#645]
[This recent update](https://github.com/PolymerElements/iron-form-element-behavior/commit/664f99e825a3ee877aa6644283bfe8a8708dcde5) in `iron-form-element-behavior` breaks the TypeScript compilation:

The `value` property was changed from …

```
value: string|null|undefined;
```
… to …
```
value: string|number|null|undefined;
```

Which produces the following error:

```
error TS2320: Interface 'PaperInputElement' cannot simultaneously extend types 'PaperInputBehavior' and 'IronFormElementBehavior'.
  Named property 'value' of types 'PaperInputBehavior' and 'IronFormElementBehavior' are not identical.
```

Fix should be as easy as updating the corresponding definition in `paper-input` accordingly. However, I'm not sure whether the dependency version here should be adjusted as well? Strictly speaking, this looks like a breaking change from a TS perspective to me.

**Comment by notwaldorf** [comment]
cc @TimvdLippe who did the change and @aomarks who speaks TS

**Comment by TimvdLippe** [comment]
Ah that is unfortunate, this was not intended as a breaking change. I will
likely need to update all usages of IronFormElementBehavior to fix it. Will
work on it asap.

**Comment by floribon** [comment]
This break also affected our team, thanks @qqilihq for finding the root cause and Polymer team for looking into it.

My current workaround is to force install the previous version in my bower.json:
> "iron-form-element-behavior": "PolymerElements/iron-form-element-behavior#2.1.1"

**Comment by ahmadhsalim** [comment]
for me I had to rollback app-layout to previous version as well
`"app-layout": "PolymerElements/app-layout#2.0.5"`

**Comment by TimvdLippe** [comment]
@ahmadhsalim Hm I am not sure how that would work out, as that element has no dependency on the behavior? https://github.com/PolymerElements/app-layout/blob/master/bower.json

**Comment by TvrtkoM** [comment]
Out of curiosity - when is this fix going to be released? I have the same issue with paper-input@2.2.2 which is installed with npm
