### ISSUE TITLE
Dependency not found 404 error (breaks program when using paper-input)

### ISSUE THREAD

**Issue by colincannon-acp** [PolymerElements/paper-input#653]
### Description

Importing the paper-input element causes a 404 error and brings the program execution to a halt when using the polymer 3 starter kit.

### Expected outcome

I expect to be able to import paper-input with not 404 errors.

### Actual outcome

Here is a picture of the error after including the following line (
import '@polymer/paper-input/paper-input.js';):

![screen shot 2018-05-22 at 8 54 53 am](https://user-images.githubusercontent.com/6200810/40363751-74f28adc-5d9e-11e8-926f-37aa08387df3.png)

It looks like it is looking for iron-validatable-behavior in the wrong spot

### Steps to reproduce

1.  Use npm to get paper-input
2.  Import paper-input into your project
3.  The 404 error occurs when paper-input looks for the dependency: iron-validatable-behavior

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
Are you using the correct import? It sounds like you're not, and i can't tell what's going on without a code sample

**Comment by notwaldorf** [comment]
Closing this since there are no repro steps; please provide a demo somewhere on jsbin, glitch, stackblitz, etc so we can take a look at.
