### ISSUE TITLE
Missing paper-input-container documentation

### ISSUE THREAD

**Issue by wojinwomacka** [PolymerElements/paper-input#656]
### Description
Since version 2.2.0 is out, documentation on [webcomponents.org](https://www.webcomponents.org/element/PolymerElements/paper-input/elements/paper-input-container) is missing almost all sections including styling, description, validation, add-ons and so on..

### Expected outcome
Documentation should be same as in previous versions. For example: https://www.webcomponents.org/element/PolymerElements/paper-input/v2.1.1/elements/paper-input-container

### Actual outcome

Almost all sections in documentation are missing. 

### Live Demo
https://www.webcomponents.org/element/PolymerElements/paper-input/elements/paper-input-container

**Comment by notwaldorf** [comment]
cc @samuelli

**Comment by wojinwomacka** [comment]
@notwaldorf  I hope you know about the current state of documentation (2.2.4).. it's broken much more than previously. At this moment, section 'elements' is missing. Only section overview is visible

**Comment by samuelli** [comment]
Fixed in the latest update now!
