### ISSUE TITLE
Error message does not show up in Safari

### ISSUE THREAD

**Issue by atotic** [PolymerElements/paper-input#67]
Error message does not show up:

       <paper-input
          id="password"
          label="password"
          error-message="required"
          required></paper-input>

**Comment by atotic** [comment]
or Firefox

**Comment by notwaldorf** [comment]
I think you need to add `auto-validate`, to actually trigger validation, or manually call `validate()`.

**Comment by atotic** [comment]
Oh, I do. It works in Chrome, just does not show up in FF or Safari

**Comment by morethanreal** [comment]
Hmm, it works for me and there is a test case for it: https://github.com/PolymerElements/paper-input/blob/master/test/paper-input.html#L122.

**Comment by atotic** [comment]
I've just tried it again, and now it works. I've bower install'd since, might have been that..... Thanks for looking.
