### ISSUE TITLE
invalid is false even when error message is showing

### ISSUE THREAD

**Issue by atotic** [PolymerElements/paper-input#68]
If you call paper-input.validate(), and the value is invalid (required and missing), error message shows up, but paper-input.invalid is false. I'd expect invalid to be true if errors are showing up.

        <paper-input
          id="username"
          label="username"
          error-message="required"
          required></paper-input>
        
       this.$.username.validate();

       this.$.username.invalid is false, should be true

sorry, no testcase, still trying to figure out how use paper-input on jsbin.

**Comment by atotic** [comment]
the iron-input invalid is true at the time, suspect iron-input is not propagating paper-input

**Comment by morethanreal** [comment]
Seems like `invalid` needs `notify:true`. Fix is in https://github.com/PolymerElements/iron-validatable-behavior/pull/8

**Comment by morethanreal** [comment]
Should be fixed, test case here: https://github.com/PolymerElements/paper-input/pull/76
