### ISSUE TITLE
Float label blocks type="date" placeholder on chrome

### ISSUE THREAD

**Issue by makrolabs** [PolymerElements/paper-input#71]
<paper-input type="date" label="Test"></paper-input>

I think the correct behaviour is for the label to always be floating at the top when the type is date.

**Comment by morethanreal** [comment]
You can set the `always-float-label` attribute to float the label.

**Comment by makrolabs** [comment]
Thanks, note the always-float-label attribute does not work when applying to paper-input:
<paper-input type="date" label="test" always-float-label></paper-input>

only with paper-input-container and iron-input: 
<paper-input-container always-float-label>
    <label>test</label>
    <input is="iron-input" type="date">
</paper-input-container>

**Comment by morethanreal** [comment]
Yup, that was a bug fixed in https://github.com/PolymerElements/paper-input/pull/75
