### ISSUE TITLE
[1.0] paper-input .focus(), .blur()

### ISSUE THREAD

**Issue by kirilledelman** [PolymerElements/paper-input#87]
Unable to set focus on input by calling `paperInputInstance.focus()`.

Workaround is to call it directly on its input field:
`paperInputInstance.$.input.focus()`

Same goes for .blur().

Additionally, `on-focus`, and `on-blur` don't work on `paper-input`.

**Comment by morethanreal** [comment]
The `inputElement` property will give you the `<input>` element and it is the preferred way to invoke methods on the input element directly. e.g. `paperInputInstance.inputElement.focus()`.

`blur` and `focus` events should be fired on `<paper-input>` as of https://github.com/PolymerElements/paper-input/commit/92b3c42c792f615a0f387cce1105c33a331d6ed2.

**Comment by RuedigerMoeller** [comment]
does not work with 1.016 - regression ?

**Comment by dbrans** [comment]
This appears to still be the case in "1.9.1".

**Comment by AliMD** [comment]
Not work for me event with `paperInputInstance.inputElement.focus()` in `paper-input v2`
I need to use double `inputElement` to fix issue like this
```
this.$.myInput.inputElement.focus(); // not work in v2
if (this.$.myInput.inputElement.inputElement) {
  this.$.myInput.inputElement.inputElement.focus();
}
```
