### ISSUE TITLE
[1.0] paper-input autocorrect, autocapitalize attributes

### ISSUE THREAD

**Issue by kirilledelman** [PolymerElements/paper-input#88]
It would be swell if `autocorrect="off"` and `autocapitalize="off"` were available on paper-input. I'm having to set these on `$.input` manually in code. These are very useful for form fields on mobile.

**Comment by atotic** [comment]
Also: autocomplete, spellcheck

**Comment by morethanreal** [comment]
Fixed via #100.

**Comment by atotic** [comment]
What aobut autocomplete, spellcheck attributes? Also needed on ios, hate getting my login id spellchecked.

**Comment by notwaldorf** [comment]
@atotic 'autocomplete` is already an attribute. Please file another issue if there's other attributes you need other than just reopening this one and adding more things, since this makes triaging a nightmare :)
