### ISSUE TITLE
Prevent tracking inside a `paper-input`

### ISSUE THREAD

**Issue by azakus** [PolymerElements/paper-input#89]
Polymer 1.0.4 landed user prevention of gestures.

Ideally, inputs should prevent tracking when a user starts in an input.

Example:
```js
downHandler: function(e, detail) {
  detail.prevent('track');
}
```

**Comment by notwaldorf** [comment]
@azakus Going to pass this to you. Is this still an issue?

**Comment by azakus** [comment]
Meh, probably not a real issue in practice.

Feel free to reopen / bug me if this isn't the case.
