### ISSUE TITLE
label bug

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/paper-input#93]
Label doesn't do what it supposed to be doing like the other inputs

```html
<paper-input-container>
       <label>Intoductie</label>
       <iron-autogrow-textarea id="a1" style="font:inherit;">
                <textarea id="t1" name="intro"></textarea>
       </iron-autogrow-textarea>
 </paper-input-container>
```
![image](https://cloud.githubusercontent.com/assets/863731/8265277/76e60c5c-16f6-11e5-8b2d-6c197dd85829.png)

**Comment by gertcuykens** [comment]
Fix
```html
<paper-input-container>
         <iron-autogrow-textarea id="a1" style="font:inherit;" placeholder="Intoductie">
                    <textarea id="t1" name="intro"></textarea>
         </iron-autogrow-textarea>
</paper-input-container>
```

Yes I stil think the above should work too :P

**Comment by notwaldorf** [comment]
You can just use a `paper-textarea`, which does all that wrapping for you (see the code in the demo for an example)

**Comment by gertcuykens** [comment]
DOH!

**Comment by gertcuykens** [comment]
Wait a minute `paper-textarea` does not exist!

**Comment by gertcuykens** [comment]
Never mind... still think it should be a separate element like the others
