### ISSUE TITLE
Extra space created by auto validation error = BAD

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/paper-input#95]
https://github.com/Polymer/paper-input/issues/171

Elements above and below do not jump around to create extra space for the floating label = GOOD
![image](https://cloud.githubusercontent.com/assets/863731/8265696/b25c3a5e-1705-11e5-8a7e-8babb0d43597.png)

This auto validation make me seasick because the elements below jump all over the place when you fill in a form = BAD
![image](https://cloud.githubusercontent.com/assets/863731/8265694/8e4a55ce-1705-11e5-911e-83950c297575.png)

**Comment by notwaldorf** [comment]
Do you have a jsbin where you can repro this? If you look at the `paper-input` [demo](https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html) and scroll down to the Validation section, typing numbers in the auto-validate field will make the error message show up, but the layout doesn't change.

**Comment by gertcuykens** [comment]
Even better :) see demo page 
 https://www.polymer-project.org/1.0/components/paper-input/demo.html 

![image](https://cloud.githubusercontent.com/assets/863731/8319397/98bd50f4-1a0e-11e5-8941-13f9df8b22b9.png)

![image](https://cloud.githubusercontent.com/assets/863731/8319410/c8300318-1a0e-11e5-8cbf-a3a839baa332.png)

**Comment by gertcuykens** [comment]
Floating labels are designed to accommodate the space needed = GOOD

![image](https://cloud.githubusercontent.com/assets/863731/8319521/1d96811e-1a10-11e5-9301-5f9a460aa0a9.png)

----------------------------------------

![image](https://cloud.githubusercontent.com/assets/863731/8319515/0df7152a-1a10-11e5-8020-6e45950bbe39.png)

**Comment by gertcuykens** [comment]
Let me know if it is clear now thanks
