### ISSUE TITLE
Animation not working with type="number"

### ISSUE THREAD

**Issue by jscissr** [PolymerElements/paper-input#99]
The focus animation, floating label animation and other stuff is broken since 1.0.4. I confirmed that it worked in 1.0.3.
See https://github.com/PolymerElements/paper-input/commit/911f56bdc7aef2873e32c9c0b65df7088a023cd9#commitcomment-11789462

**Comment by siancu** [comment]
Same for me and #98 doesn't seem to fix these. It just fixes the required behavior of the paper-input element inside of the form.

**Comment by atoy40** [comment]
With 1.0.5, animation works for label, but label and bottom line aren't styled (color).

**Comment by jscissr** [comment]
Now I see, the label animation only doesn't work if `type="number"`. This problem is too since 1.0.4.

**Comment by siancu** [comment]
And for me there is also no line animation.

**Comment by GabiAxel** [comment]
Experiencing the same in 1.0.4+ and also on Firefox the text cursor is invisible.
